var alias_dict = {
    's': 'subject',
    'o': 'object',
    'p': 'predicate',
    'pa': 'predicate accusative',
    'sa': 'subject accusative of an indirect statement',
    'sa not is': 'subject accusative of an infinitive not in indirect statement',
    'ind': 'indicative',
    'subj': 'subjunctive',
    'subjunct': 'subjunctive',
    'inf': 'infinitive',
    'ss': 'secondary',
    'ps': 'primary',
    'secondary sequence': 'secondary',
    'primary sequence': 'primary',
    'subject': 'subject nominative',
    'object': 'accusative direct object',
    'predicate': 'predicate nominative',
    'proviso': 'proviso clause',
    'pres': 'present',
    'simultaneous': 'simultaneous time',
    'char': 'relative clause of characteristic',
    'simul': 'simultaneous time',
    'prior': 'prior time',
    'purpose': 'purpose clause',
    'rel purpose': 'relative clause of purpose',
    'am': 'ablative of means',
    'means': 'ablative of means',
    'manner': 'ablative of manner',
    'juss': 'jussive',
    'comp': 'compound',
    'compound': 'dative with compound verbs',
    'part': 'partitive',
    'partitive': 'partitive genitive',
    'abs': 'ablative subject in an ablative absolute',
    'abp': 'ablative predicate in an ablative absolute',
    'adv acc': 'adverbial accusative',
    'is': 'indirect statement',
    'iq': 'indirect question',
    'ic': 'indirect command',
    'si': 'subject infinitive',
    'fmv': "protasis/apodosis of a future more vivid conditional sentence",
	'fmv emph': "protasis/apodosis of a future more vivid conditional sentence with emphatic protasis",
	'flv': "protasis/apodosis of a future less vivid conditional sentence",
	'pres ctf': "protasis/apodosis of a present contrary to fact conditional sentence",
	'present ctf': 'pres ctf',
	'past ctf': "protasis/apodosis of a past contrary to fact conditional sentence",
	'mixed ctf': "protasis/apodosis of a mixed contrary to fact conditional sentence",
	'abl ell spat': "ablative with ellipsed spatial preposition",
	"pres subj": "pres & subj & ps & simul",
	"imp subj": "imperfect & subj & ss & simul",
	"perf subj": "perfect & subj & ps & prior",
	"plu subj": "pluperfect & subj & ss & prior",
	"pluperf subj": "plu subj",
	"rel cause": "relative clause of cause",
	"sec gen": "2nd singular generalizing subjunctive",
	"delib": "deliberative",
	"d adv": "dative of advantage/disadvantage/separation"
}