var alias_dict = {
    'abl cause': 'ablative of cause',
    'abl comp': 'ablative of comparison',
    'abl ell spat': 'ablative with ellipsed spatial preposition',
    'abp': 'ablative predicate in an ablative absolute',
    'abs': 'ablative subject in an ablative absolute',
    'adv acc': 'adverbial accusative',
    'am': 'ablative of means',
    'char': 'relative clause of characteristic',
    'comp': 'compound',
    'compound': 'dative with compound verbs',
    'd adv': 'dative of advantage/disadvantage/separation',
    'dat intrans': 'dative with certain intransitive verbs',
    'dat poss': 'dative of possessor',
    'delib': 'deliberative',
    'fear clause': '^it & subsequent time!10',
    'flv': 'protasis/apodosis of a future less vivid conditional sentence',
    'fmv': 'protasis/apodosis of a future more vivid conditional sentence',
    'fmv emph': 'protasis/apodosis of a future more vivid conditional sentence with emphatic protasis',
    'fp': 'future_perfect',
    'hortatory': '^it & no sequence & no relative time!10',
    'ic': 'indirect command',
    'imp subj': 'imperfect & subj & ss & simul',
    'imperfect subjunctive': 'imp subj',
    'ind': 'indicative',
    'indirect command': '^it & subsequent time!10',
    'indirect statement': '^it & no sequence!10',
    'inf': 'infinitive',
    'iq': 'indirect question',
    'iq orig del': 'indirect question standing in for original deliberative',
    'is': 'indirect statement',
    'juss': 'jussive',
    'jussive': '^it & no sequence & no relative time!10',
    'manner': 'ablative of manner',
    'means': 'ablative of means',
    'mixed ctf': 'protasis/apodosis of a mixed contrary to fact conditional sentence',
    'o': 'object',
    'object': 'accusative direct object',
    'p': 'predicate',
    'p subj': 'pres subj',
    'pa': 'predicate accusative',
    'part': 'partitive genitive',
    'partitive': 'partitive genitive',
    'past ctf': 'protasis/apodosis of a past contrary to fact conditional sentence',
    'past deliberative': '^it & & ^imperfect & ^subjunctive & no sequence & no relative time!10',
    'past optative - wish incapable of fulfillment': '^it & ^pluperfect & ^subjunctive & no sequence & no relative time!10',
    'past potential': '^it & & ^imperfect & ^subjunctive & no sequence & no relative time!10',
    'perf subj': 'perfect & subj & ps & prior',
    'perfect subjunctive': 'perf subj',
    'plu subj': 'pluperfect & subj & ss & prior',
    'pluperf subj': 'plu subj',
    'pluperfect subj': 'plu subj',
    'potential': '^it & no sequence & no relative time!10',
    'predicate': 'predicate nominative',
    'pres': 'present',
    'pres ctf': 'protasis/apodosis of a present contrary to fact conditional sentence',
    'pres subj': 'pres & subj & ps & simul',
    'present ctf': 'pres ctf',
    'present deliberative': '^it & ^present & ^subjunctive & no sequence & no relative time!10',
    'present optative - wish capable of fulfillment': '^it & ^present & ^subjunctive & no sequence & no relative time!10',
    'present optative - wish incapable of fulfillment': '^it & ^imperfect & ^subjunctive & no sequence & no relative time!10',
    'present potential': '^it & ^present & ^subjunctive & no sequence & no relative time!10',
    'present subjunctive': 'pres subj',
    'pressubj': 'pres & subj & ps & simul',
    'prevention clause': '^it & subsequent time!10',
    'primary sequence': 'primary',
    'prior': 'prior time',
    'protasis/apodosis of a future less vivid conditional sentence': '^it & no sequence & no relative time!10',
    'protasis/apodosis of a future more vivid conditional sentence': '^it & no sequence & no relative time!10',
    'protasis/apodosis of a future more vivid conditional sentence with emphatic protasis': '^it & no sequence & no relative time!10',
    'protasis/apodosis of a mixed contrary to fact conditional sentence': '^it & no sequence & no relative time!10',
    'protasis/apodosis of a past contrary to fact conditional sentence': '^it & no sequence & no relative time!10',
    'protasis/apodosis of a present contrary to fact conditional sentence': '^it & no sequence & no relative time!10',
    'proviso': 'proviso clause',
    'ps': 'primary',
    'purpose': 'purpose clause',
    'purpose clause': '^it & subsequent time!10',
    'rel cause': 'relative clause of cause',
    'rel purpose': 'relative clause of purpose',
    'relative clause of purpose': '^it & subsequent time!10',
    'relative clause of result': '^it & subsequent time!10',
    'result clause': '^it & subsequent time!10',
    's': 'subject',
    'sa': 'subject accusative of an indirect statement',
    'sa not is': 'subject accusative of an infinitive not in indirect statement',
    'sec gen': '2nd singular generalizing subjunctive',
    'secondary sequence': 'secondary',
    'sep': 'ablative of separation',
    'si': 'subject infinitive',
    'simul': 'simultaneous time',
    'simultaneous': 'simultaneous time',
    'ss': 'secondary',
    'subj': 'subjunctive',
    'subject': 'subject nominative',
    'subjunct': 'subjunctive',
    'subseq': 'subsequent time',
    'subsequent': 'subsequent time',
    'subst ut': 'substantive ut',
    'substantive ut': 'substantive ut clause'
}