var latin_words_in_mf = [
'unit^%^^,^^,^^,^^gen^^part of speech, (excluding nouns, adjectives and verbs)^definition^#^conj/decl^#^pos^#^voc notes^supplementary roots^cognates', 
'1^%^ambulō^,^ambul$āre^,^ambulāv$ī^,^ambulāt$us^^*^^walk^#^1^#^verb^#^^^ambulance', 
'1^%^aqua^,^aqu$ae^,^^,^^f.^*^^water^#^1^#^noun^#^^^aquatic, aquarium', 
'1^%^clāmō^,^clām$āre^,^clāmāv$ī^,^clāmāt$us^^*^^shout^#^1^#^verb^#^^^exclamation', 
'1^%^corōna^,^corōn$ae^,^^,^^f.^*^^crown, wreath^#^1^#^noun^#^^^', 
'1^%^corōnō^,^corōn$āre^,^corōnāv$ī^,^corōnāt$us^^*^^^#^^#^verb^#^^^', 
'1^%^cum^,^^,^^,^^^*^^with^#^^#^prep.^#^+ abl.^^summa cum laude', 
'1^%^cūra^,^cūr$ae^,^^,^^f.^*^^care, concern, anxiety^#^1^#^noun^#^^^pedicure, manicure', 
'1^%^dē^,^^,^^,^^^*^^concerning, about; (down) from^#^^#^prep^#^+ abl.^^degradation', 
'1^%^dō^,^dare^,^ded$ī ^,^dat$us^^*^^give, grant [allow?]^#^^#^verb^#^acc + dat, do + infin = allow to …^^', 
'1^%^dōnō^,^dōn$āre^,^dōnāv$ī^,^dōnāt$us^^*^^give, present, reward^#^1^#^verb^#^acc + dat or acc + abl.^^donation, donor', 
'1^%^ē, ex^,^^,^^,^^^*^^out of, from^#^^#^prep^#^+ abl.^^', 
'1^%^enim^,^^,^^,^^^*^^indeed, of course; for^#^^#^coordinating conjunction (postpositive)^#^^^', 
'1^%^et^,^^,^^,^^^*^^^#^^#^coordinating conjunction or adverb^#^et (adv) = even', 
'et…et = both…and …^^', 
'1^%^fāma^,^fām$ae^,^^,^^f.^*^^talk, report, rumor, fame, reputation^#^^#^noun^#^^^famous', 
'1^%^fēmina^,^fēmin$ae^,^^,^^f.^*^^woman^#^1^#^noun^#^^^feminine', 
'1^%^fōrma^,^fōrm$ae^,^^,^^f.^*^^figure, shape, figure, beauty^#^1^#^noun^#^^^', 
'1^%^habeō^,^hab$ēre^,^habu$ī^,^habit$us^^*^^have, hold, possess, consider^#^2^#^verb^#^^^', 
'1^%^impleō^,^impl$ēre^,^implēv$ī^,^implēt$us^^*^^fill, fill up^#^^#^verb^#^^^', 
'1^%^in^,^^,^^,^^^*^^into, onto (w/ acc.); in, on (w/ abl)^#^^#^prep.^#^+acc/abl^^', 
'1^%^īnsula^,^īnsul$ae^,^^,^^f.^*^^island^#^^#^noun^#^^^', 
'1^%^nauta^,^naut$ae^,^^,^^m. ^*^^sailor^#^^#^noun^#^^^', 
'1^%^-ne^,^^,^^,^^^*^^indicates a question^#^^#^enclitic^#^^^', 
'1^%^nōn^,^^,^^,^^^*^^not^#^^#^adverb^#^^^', 
'1^%^optō^,^opt$āre^,^optāv$ī^,^optāt$us^^*^^desire, wish (for); choose^#^^#^verb^#^^^', 
'1^%^patria^,^patri$ae^,^^,^^f.^*^^native land, country^#^^#^noun^#^^^', 
'1^%^pecūnia^,^pecūni$ae^,^^,^^f.^*^^money^#^^#^noun^#^> pecus (flock, herd) suggests an origin of money in cattle^^', 
'1^%^poena^,^poen$ae^,^^,^^f.^*^^penalty^#^^#^noun^#^^^', 
'1^%^poenās dare^,^^,^^,^^^*^^to pay a penalty^#^^#^idiom^#^idiom^^', 
'1^%^poēta^,^poēt$ae^,^^,^^m.^*^^poet^#^^#^noun^#^^^', 
'1^%^porta^,^port$ae^,^^,^^f.^*^^gate^#^^#^noun^#^^^', 
'1^%^-que^,^^,^^,^^^*^^and^#^^#^enclitic^#^^^', 
'1^%^rēgīna^,^rēgīn$ae^,^^,^^f.^*^^queen^#^^#^^#^^^', 
'1^%^sed^,^^,^^,^^^*^^but^#^^#^coordinating conjunction^#^^^', 
'1^%^sum^,^esse^,^fu$ī^,^futūr$us^^*^^be, exist^#^^#^verb^#^^^', 
'1^%^taeda^,^taed$ae^,^^,^^f.^*^^torch^#^^#^^#^^^', 
'1^%^terreō^,^terr$ēre^,^terru$ī^,^territ$us^^*^^frighten, alarm, terrify^#^^#^verb^#^^^', 
'1^%^timeō^,^tim$ēre^,^timu$ī^,^--^^*^^fear, be afraid (of)^#^^#^verb^#^^^', 
'1^%^turba^,^turb$ae^,^^,^^f.^*^^crowd, uproar^#^^#^noun^#^^^', 
'1^%^via^,^vi$ae^,^^,^^f.^*^^way, road, path, street^#^^#^noun^#^^^', 
'1^%^videō^,^vid$ēre^,^vīd$ī^,^vīs$us^^*^^see^#^^#^verb^#^^^', 
'^%^***^,^^,^^,^^^*^^^#^^#^^#^^^', 
'2^%^ā/ab^,^^,^^,^^^*^^(away) from; by (only with living beings)^#^^#^preposition^#^+abl.^^', 
'2^%^ad^,^^,^^,^^^*^^to, toward^#^^#^preposition^#^+ acc.^^ad hominem', 
'2^%^anima^,^anim$ae^,^^,^^f.^*^^soul, spirit, life force^#^1^#^noun^#^^^animism, animate', 
'2^%^āra^,^ār$ae^,^^,^^f.^*^^altar^#^1^#^noun^#^^^', 
'2^%^capiō^,^cap$ere^,^cēp$ī^,^capt$us^^*^^take, capture^#^3i^#^verb^#^^^', 
'2^%^cella^,^cell$ae^,^^,^^f.^*^^storeroom, (small) room^#^1^#^noun^#^^^', 
'2^%^cēlō^,^cēl$āre^,^cēlāv$ī^,^cēlāt$us^^*^^hide, conceal^#^1^#^verb^#^^^', 
'2^%^cōgitō^,^cōgit$āre^,^cōgitāv$ī^,^cōgitāt$us^^*^^think, ponder, consider^#^1^#^verb^#^^^', 
'2^%^culpa^,^culp$ae^,^^,^^f.^*^^guilt, fault^#^1^#^noun^#^^^mea culpa', 
'2^%^dāmnō^,^dāmn$āre^,^dāmnāv$ī^,^dāmnāt$us^^*^^condemn, sentence^#^1^#^verb^#^^^', 
'2^%^dubitō^,^dubit$āre^,^dubitāv$ī^,^dubitāt$us^^*^^doubt, hesitate^#^1^#^verb^#^^^', 
'2^%^glōria^,^glōri$ae^,^^,^^f.^*^^glory, renown^#^1^#^noun^#^^^', 
'2^%^incipiō^,^incip$ere^,^incēp$ī^,^incept$us^^*^^begin^#^3i^#^verb^#^^^', 
'2^%^incola^,^incol$ae^,^^,^^m. (occasionally f.)^*^^inhabitant^#^1^#^noun^#^^^', 
'2^%^incolō^,^incol$ere^,^incolu$ī^,^--^^*^^inhabit^#^3^#^verb^#^^^', 
'2^%^īnsidiae^,^īnsidi$ārum^,^^,^^f. pl.^*^^ambush, plot, treachery^#^1^#^noun^#^^^pl. in form but singular in meaning', 
'2^%^invidia^,^invidi$ae^,^^,^^f.^*^^envy, jealousy^#^1^#^noun^#^^^', 
'2^%^labōrō^,^labōr$āre^,^labōrāv$ī^,^labōrāt$us^^*^^work^#^1^#^verb^#^^^', 
'2^%^lacrima^,^lacrim$ae^,^^,^^f.^*^^tear (as in teardrop)^#^1^#^noun^#^^^', 
'2^%^lūna^,^lūn$ae^,^^,^^f.^*^^moon^#^1^#^noun^#^^^', 
'2^%^moneō^,^mon$ēre^,^monu$ī^,^monit$us^^*^^warn, remind^#^2^#^verb^#^^^', 
'2^%^mora^,^mor$ae^,^^,^^f.^*^^delay^#^1^#^noun^#^^^', 
'2^%^mūtō^,^mūt$āre^,^mūtāv$ī^,^mūtāt$us^^*^^change, exchange^#^1^#^verb^#^^^', 
'2^%^nātūra^,^nātūr$ae^,^^,^^f.^*^^nature^#^1^#^noun^#^^^', 
'2^%^neque/nec^,^^,^^,^^^*^^and not^#^^#^coordinating conjunction^#^^^', 
'2^%^neque…neque…^,^^,^^,^^^*^^neither..nor…^#^^#^coordinating conjunction^#^^^', 
'2^%^nec…nec…^,^^,^^,^^^*^^neither..nor…^#^^#^coordinating conjunction^#^^^', 
'2^%^nihil/nīl^,^^,^^,^^n.^*^^^#^n/a^#^noun (indeclinable)^#^indeclinable (until ch….)^^', 
'2^%^nisi^,^^,^^,^^^*^^unless, if…not; except^#^^#^subordinating conjunction^#^typo in the book^^', 
'2^%^noxa^,^nox$ae^,^^,^^f.^*^^harm, injury^#^1^#^noun^#^^^', 
'2^%^nunc^,^^,^^,^^^*^^now^#^^#^adverb^#^^^', 
'2^%^pellō^,^pell$ere^,^pepul$ī^,^puls$us^^*^^push, drive (off)^#^3^#^verb^#^reduplication (common in IE languages)^^', 
'2^%^expellō^,^expell$ere^,^expul$ī^,^expuls$us^^*^^^#^3^#^verb^#^compound verbs sometimes lose their reduplication^^', 
'2^%^per^,^^,^^,^^^*^^^#^^#^preposition^#^^^', 
'2^%^prōvincia^,^prōvinci$ae^,^^,^^f.^*^^province^#^1^#^noun^#^> vinco^^', 
'2^%^puella^,^puell$a^,^^,^^f.^*^^girl^#^1^#^noun^#^^^', 
'2^%^semper^,^^,^^,^^^*^^always^#^^#^adverb^#^^^', 
'2^%^sententia^,^sententi$ae^,^^,^^f.^*^^feeling, thought, opinion^#^1^#^noun^#^^^', 
'2^%^sentiō^,^sent$īre^,^sēns$ī^,^sēns$us^^*^^feel, perceive^#^4^#^verb^#^^^', 
'2^%^sī^,^^,^^,^^^*^^if^#^^#^subordinating conjunction^#^^^', 
'2^%^sub^,^^,^^,^^+acc/abl^*^^under^#^^#^preposition^#^stationary/motion^^', 
'2^%^superō^,^super$āre^,^superāv$ī^,^superāt$us^^*^^overcome, conquer^#^1^#^verb^#^^^', 
'2^%^taceō^,^tac$ēre^,^tacu$ī^,^tacit$us^^*^^be (or keep) silent^#^2^#^verb^#^^^', 
'2^%^teneō^,^ten$ēre^,^tenu$ī^,^tent$us^^*^^hold, keep, possess^#^2^#^verb^#^^^', 
'2^%^terra^,^terr$ae^,^^,^^f.^*^^earth, land^#^1^#^noun^#^^^', 
'2^%^unda^,^und$ae^,^^,^^f.^*^^wave^#^1^#^noun^#^^^', 
'2^%^veniō^,^ven$īre^,^vēn$ī^,^vent$us^^*^^come^#^4^#^verb^#^^^', 
'^%^vīta^,^vīt$ae^,^^,^^f.^*^^life^#^1^#^noun^#^^^', 
'^%^***^,^^,^^,^^^*^^^#^^#^^#^^^', 
'3^%^acerbus^,^acerb$a^,^acerbum^,^^^*^^bitter, harsh^#^2/1/2^#^adjective^#^^^', 
'3^%^ager^,^agr$ī^,^^,^^m.^*^^field^#^2^#^noun^#^^^', 
'3^%^audiō^,^aud$īre^,^audīv$ī^,^audīt$us^^*^^hear, listen (to)^#^4^#^verb^#^^^', 
'3^%^bellum^,^bell$ī^,^^,^^n.^*^^war^#^2^#^noun^#^^^', 
'3^%^bonus^,^bon$a^,^bonum^,^^^*^^good^#^2/1/2^#^adjective^#^^^', 
'3^%^caecus^,^caec$a^,^caecum^,^^^*^^blind, hidden, secret^#^2/1/2^#^adjective^#^^^', 
'3^%^campus^,^camp$ī^,^^,^^m.^*^^plain, level surface^#^2^#^noun^#^^^', 
'3^%^clārus^,^clār$a^,^clārum^,^^^*^^bright, clear, famous^#^2/1/2^#^adjective^#^^^', 
'3^%^dexter^,^dextr#a^,^dextrum^,^^^*^^right (as opposed to left), favorable^#^2/1/2^#^adjective^#^^^', 
'3^%^dextra^,^dextrae^,^^,^^f.^*^^right hand^#^1^#^noun^#^^^', 
'3^%^ad dextram^,^^,^^,^^^*^^to the right^#^^#^^#^^^', 
'3^%^dīligentia^,^dīligenti$ae^,^^,^^f.^*^^diligence^#^1^#^noun^#^^^', 
'3^%^dōnum^,^dōn$ī^,^^,^^n.^*^^gift^#^2^#^noun^#^^^', 
'3^%^gerō^,^ger$ere^,^gess$ī^,^ges$tus^^*^^conduct, manage, wage^#^3^#^verb^#^^^', 
'3^%^gladius^,^gladiī^,^^,^^m.^*^^sword^#^2^#^noun^#^^^', 
'3^%^laetus^,^laet$a^,^laetum^,^^^*^^happy^#^2/1/2^#^adjective^#^^^', 
'3^%^līber^,^līber$a^,^līberum^,^^^*^^free^#^2/1/2^#^adjective^#^^^', 
'3^%^magnus^,^magn$a^,^magnum^,^^^*^^large, big, great^#^2/1/2^#^adjective^#^^^', 
'3^%^malus^,^mal$a^,^malum^,^^^*^^evil, bad, wicked^#^2/1/2^#^adjective^#^^^', 
'3^%^Marcus^,^Marc$ī^,^^,^^m.^*^^Marcus (proper name)^#^2^#^noun^#^^^', 
'3^%^miser^,^miser$a^,^miserum^,^^^*^^miserable, unhappy, wretched^#^2/1/2^#^adjective^#^^^', 
'3^%^multus^,^mult$a^,^multum^,^^^*^^much, many^#^2/1/2^#^adjective^#^can be used in singular: multa puella = “many a girl)^^', 
'3^%^nātus^,^nāt$ī^,^^,^^m.^*^^son^#^1^#^noun^#^^^', 
'3^%^nē^,^^,^^,^^^*^^^#^^#^^#^in order that…not', 
'that…not^^', 
'3^%^oculus^,^ocul$ī^,^^,^^m.^*^^eye^#^2^#^noun^#^^^', 
'3^%^ōrō^,^ōr$āre^,^ōrāv$ī^,^ōrāt$us^^*^^beg (for)^#^1^#^verb^#^^^', 
'3^%^petō^,^pet$ere^,^petīv$ī^,^petīt$us^^*^^seek, ask (for)^#^3^#^verb^#^ā + abl.  pecūniam ā nātō petō^^', 
'3^%^portō^,^port$āre^,^portāv$ī^,^portāt$us^^*^^carry^#^1^#^verb^#^^^', 
'3^%^puer^,^puer$ī^,^^,^^m.^*^^boy; child^#^2^#^noun^#^^^', 
'3^%^pūgnō^,^pūgn$āre^,^pūgnāv$ī^,^pūgnāt$us^^*^^fight; fight (with)^#^1^#^verb^#^^^', 
'3^%^pulcher^,^pulchr$a^,^pulchrum^,^^^*^^beautiful^#^2/1/2^#^adjective^#^^^', 
'3^%^Rōmānus^,^Rōmān$a^,^Rōmānum^,^^^*^^Roman^#^2/1/2^#^adjective^#^^^', 
'3^%^saxum^,^sax$ī^,^^,^^n.^*^^rock, stone^#^2^#^noun^#^^^', 
'3^%^scrībō^,^scrīb$ere^,^scrīps$ī^,^scrīpt$us^^*^^write^#^3^#^verb^#^^^', 
'3^%^servus^,^serv$ī^,^^,^^m.^*^^slave^#^2^#^noun^#^> servo (save) [a prisoner of war saved from being executed]^^', 
'3^%^spectō^,^spect$āre^,^spectāv$ī^,^spectāt$us^^*^^look at^#^1^#^verb^#^^^', 
'3^%^ut^,^^,^^,^^^*^^in order that…/that..^#^^#^subordinating conjunction^#^^^', 
'3^%^validus^,^valid$a^,^validum^,^^^*^^strong, healthy^#^2/1/2^#^adjective^#^^^', 
'3^%^vēlum^,^vēl$ī^,^^,^^n.^*^^cloth, covering, sail^#^2^#^noun^#^^^', 
'3^%^vēla dare^,^^,^^,^^^*^^set sail^#^^#^idiom^#^^^', 
'3^%^venia^,^veni$ae^,^^,^^f.^*^^indulgence, favor, kindness, (obliging) disposition^#^1^#^noun^#^^^', 
'3^%^ventus^,^vent$ī^,^^,^^m.^*^^wind^#^2^#^noun^#^^^', 
'3^%^verbum^,^verb$ī^,^^,^^n.^*^^word^#^2^#^noun^#^^^', 
'3^%^vir^,^vir$ī^,^^,^^m.^*^^man^#^2^#^noun^#^^^virility', 
'^%^***^,^^,^^,^^^*^^^#^^#^^#^^^', 
'4^%^aeternus^,^aetern$a^,^aeternum^,^^^*^^eternal^#^2/1/2^#^adjective^#^^^', 
'4^%^agō^,^ag$ere^,^ēg$ī^,^āct$us^^*^^do, drive, discuss, spend(time), conduct^#^3^#^verb^#^^^', 
'4^%^altus^,^alt$a^,^altum^,^^^*^^high, tall, deep^#^2/1/2^#^adjective^#^^^', 
'4^%^amīcus^,^amīc$a^,^amīcum^,^^^*^^friendly (+dat)^#^2/1/2^#^adjective^#^+ dat^^', 
'4^%^inimīcus^,^inimīc$a^,^inimīcum^,^^^*^^unfriendly, hostile (+dat)^#^2/1/2^#^adjective^#^+ dat^^', 
'4^%^caelum^,^cael$ī^,^^,^^n.^*^^heaven, sky^#^2^#^noun^#^^^', 
'4^%^cārus^,^cār$a^,^cārum^,^^^*^^dear (+dat)^#^2/1/2^#^adjective^#^+ dat^^', 
'4^%^cibus^,^cib$ī^,^^,^^m.^*^^food^#^2^#^noun^#^^^', 
'4^%^circum^,^^,^^,^^^*^^around^#^^#^preposition^#^+ acc^^', 
'4^%^dēleō^,^dēl$ēre^,^dēlēv$ī^,^dēlēt$us^^*^^destroy^#^2^#^verb^#^^^', 
'4^%^deus^,^de$ī^,^^,^^m.^*^^a god, deity^#^2^#^noun^#^^^', 
'4^%^dea^,^de$ae^,^^,^^f.^*^^goddess^#^^#^^#^^^', 
'4^%^dūcō^,^dūc$ere^,^dūx$ī^,^duct$us^^*^^lead; consider^#^3^#^verb^#^^^', 
'4^%^faciō^,^fac$ere^,^fēc$ī^,^fact$us^^*^^make, do^#^3i^#^verb^#^^^', 
'4^%^factum^,^fact$ī^,^^,^^n.^*^^deed^#^2^#^noun^#^^^', 
'4^%^fīlius^,^fīli$ī^,^^,^^m.^*^^son^#^2^#^noun^#^^^', 
'4^%^fīlia^,^fīli$ae^,^^,^^f.^*^^daughter^#^1^#^noun^#^^^', 
'4^%^honestus^,^honest$a^,^honestum^,^^^*^^respected, honorable, distinguished^#^2/1/2^#^adjective^#^^^', 
'4^%^intellegō^,^intelleg$ere^,^intellēx$ī^,^intellēct$us^^*^^understand^#^3^#^verb^#^^^', 
'4^%^legō^,^leg$ere^,^lēg$ī^,^lēct$us^^*^^choose, select; read^#^3^#^verb^#^^^', 
'4^%^liber^,^libr$ī^,^^,^^m.^*^^book^#^2^#^noun^#^^^> IE bark', 
'4^%^littera^,^litter$ae^,^^,^^f.^*^^letter (of the alphabet); pl. = letter, epistle^#^1^#^noun^#^^^', 
'4^%^mēnsa^,^mēns$ae^,^^,^^f.^*^^table^#^1^#^noun^#^^^', 
'4^%^mittō^,^mitt$ere^,^mīs$ī^,^miss$us^^*^^send^#^3^#^verb^#^^^', 
'4^%^mōnstrō^,^mōnstr$āre^,^mōnstrāv$ī^,^mōnstrāt$us^^*^^show, point out, demonstrate^#^1^#^verb^#^^^', 
'4^%^oppidum^,^oppid$ī^,^^,^^n.^*^^town^#^2^#^noun^#^^^', 
'4^%^perdō^,^perd$ere^,^perdid$ī^,^perdit$us^^*^^destroy, lose, waste^#^3^#^verb^#^^^', 
'4^%^perīculum^,^perīcul$ī^,^^,^^n.^*^^danger^#^^#^^#^^^', 
'4^%^pōnō^,^pōn$ere^,^posu$ī^,^posit$us^trans.^*^^put, place, set aside^#^3^#^verb^#^^^', 
'4^%^quod^,^^,^^,^^^*^^because^#^^#^subordinating conjunction^#^^^', 
'4^%^rēgnum^,^rēgn$ī^,^^,^^n.^*^^realm, kingdom^#^2^#^noun^#^^^', 
'4^%^respondeō^,^respond$ēre^,^respond$ī^,^respōns$us^^*^^answer^#^2^#^verb^#^^^', 
'4^%^studium^,^studi$ī^,^^,^^n.^*^^enthusiasm, zeal^#^2^#^noun^#^^^', 
'4^%^tegō^,^teg$ere^,^tēx$ī^,^tēct$us^^*^^cover, conceal^#^3^#^verb^#^^^', 
'4^%^tēctum^,^tēct$ī^,^^,^^n.^*^^roof, house^#^2^#^noun^#^^^', 
'4^%^trādō^,^trād$ere^,^trādid$ī^,^trādit$us^^*^^hand over, betray^#^3^#^verb^#^^^', 
'4^%^umbra^,^umbr$ae^,^^,^^f.^*^^shadow^#^1^#^noun^#^^^', 
'4^%^urna^,^urn$ae^,^^,^^f.^*^^urn^#^1^#^noun^#^^^', 
'4^%^vērus^,^vēr$a^,^vērum^,^^^*^^true, real^#^2/1/2^#^adjective^#^^^', 
'4^%^vērē^,^^,^^,^^^*^^truly, indeed^#^^#^adverb^#^^^', 
'4^%^vērō^,^^,^^,^^^*^^truly, indeed^#^^#^adverb^#^^^', 
'4^%^videō^,^vid$ēre^,^vīd$ī^,^vīs$us^^*^^see; passive = seem/be seen^#^2^#^verb^#^^^', 
'4^%^vīlla^,^vīll$ae^,^^,^^f.^*^^country house, farmhouse^#^^#^^#^^^', 
'^%^****^,^^,^^,^^^*^^^#^^#^^#^^^', 
'5^%^ante^,^^,^^,^^^*^^before, in front of^#^^#^prep. + acc.^#^^^', 
'5^%^ante^,^^,^^,^^^*^^before, previously^#^^#^adverb^#^^^', 
'5^%^antīquus^,^antīqu$a^,^antīquum^,^^^*^^ancient^#^2/1/2^#^adjective^#^^^', 
'5^%^ardeō^,^ard$ēre^,^ars$ī^,^ars$us^^*^^burn, be on fire; desire^#^2^#^verb^#^^^', 
'5^%^arma^,^arm$ōrum^,^^,^^n.pl.^*^^arms, weapons^#^^#^^#^^^', 
'5^%^aurum^,^aur$ī^,^^,^^n.^*^^gold^#^2^#^noun^#^^^', 
'5^%^^,^^,^^,^^^*^^^#^^#^^#^^^', 
'5^%^aureus^,^aure$a^,^aureum^,^^^*^^golden, of gold^#^2/1/2^#^adjective^#^^^', 
'5^%^autem^,^^,^^,^^^*^^however, moreover^#^^#^postpositive coordinating conjunction^#^^^', 
'5^%^bene^,^^,^^,^^^*^^well^#^^#^adv.^#^^^', 
'5^%^canō^,^can$ere^,^cecin$ī^,^cant$us^^*^^sing (of)^#^3^#^verb^#^^^', 
'5^%^cēdō^,^cēd$ere^,^cess$ī^,^cess$us^^*^^go, move, yield^#^3^#^verb^#^^^', 
'5^%^accēdō^,^accēd$ere^,^access$ī^,^access$us^^*^^to to, approach^#^3^#^verb^#^^^', 
'5^%^discēdō^,^discēd$ere^,^discess$ī^,^discess$us^^*^^go from, depart, leave^#^3^#^verb^#^^^', 
'5^%^dēbeō^,^dēb$ēre^,^dēbu$ī^,^dēbit$us^^*^^owe, ought^#^2^#^verb^#^^^', 
'5^%^dominus^,^domin$ī^,^^,^^^*^^master^#^2^#^noun^#^^^', 
'5^%^dūrus^,^dūr$a^,^dūrum^,^^^*^^hard, harsh^#^2/1/2^#^adjective^#^^^', 
'5^%^ferrum^,^ferr$ī^,^^,^^^*^^iron, sword^#^2^#^noun^#^^^', 
'5^%^flamma^,^flamm$ae^,^^,^^^*^^flame, fire^#^1^#^noun^#^^^', 
'5^%^imperium^,^imperi$ī^,^^,^^^*^^authority, power, empire^#^2^#^noun^#^^^', 
'5^%^imperō^,^imper$āre^,^imperāv$ī^,^imperāt$us^^*^^give (an) order(s), give (a) command(s)^#^1^#^verb^#^the person ordered is in the dative case; the thing ordered is expressed by an ut clause [negative nē] of indirect command^^', 
'5^%^interficiō^,^interfic$ere^,^interfēc$ī^,^interfect$us^^*^^kill^#^3i^#^verb^#^^^', 
'5^%^invādō^,^invād$ere^,^invās$ī^,^invās$us^^*^^go into, invade, attack^#^3^#^verb^#^^^', 
'5^%^magister^,^magistr$ī^,^^,^^^*^^superior, director, master, teacher^#^2^#^noun^#^^^', 
'5^%^medius^,^medi$a^,^medium^,^^^*^^middle of, middle^#^2/1/2^#^adjective^#^^^', 
'5^%^moveō^,^mov$ēre^,^mōv$ī^,^mōt$us^^*^^move^#^2^#^verb^#^^^', 
'5^%^removeō^,^remov$ēre^,^remōv$ī^,^remōt$us^^*^^remove, take away, set aside^#^2^#^verb^#^^^', 
'5^%^mox^,^^,^^,^^^*^^soon^#^^#^adv.^#^^^', 
'5^%^nōscō^,^nōsc$ere^,^nōv$ī^,^nōt$us^^*^^learn, (perfect=know)^#^3^#^verb^#^^^', 
'5^%^cognōscō^,^cognōsc$ere^,^cognōv$ī^,^cognit$us^^*^^learn, (perfect=know)^#^3^#^verb^#^^^', 
'5^%^novus^,^nov$a^,^novum^,^^^*^^new, strange^#^2/1/2^#^adjective^#^^^', 
'5^%^numquam^,^(nunquam)^,^^,^^^*^^never^#^^#^adverb^#^^^', 
'5^%^umquam^,^(unquam)^,^^,^^^*^^ever^#^^#^adverb^#^^^', 
'5^%^pius^,^pi$a^,^pium^,^^^*^^loyal, dutiful, pious^#^2/1/2^#^adjective^#^^^', 
'5^%^impius^,^impi$a^,^impius^,^^^*^^irreverent, wicked, impious^#^2/1/2^#^adjective^#^^^', 
'5^%^populus^,^popul$ī^,^^,^^m.^*^^people^#^2^#^noun^#^^^', 
'5^%^possum^,^posse^,^potu$ī^,^---^^*^^be able. can^#^(irreg.)^#^verb^#^^pot$/pos$^', 
'5^%^post^,^^,^^,^^^*^^after, behind^#^^#^preposition + acc.^#^^^', 
'5^%^post^,^^,^^,^^^*^^afterwards, after, behind^#^^#^adverb^#^^^', 
'5^%^postquam^,^^,^^,^^^*^^after^#^^#^subordinating conjunction^#^+ indicative^^', 
'5^%^quamquam^,^^,^^,^^^*^^although^#^^#^subordinating conjunction^#^+ indicative^^', 
'5^%^ruīna^,^ruīn$ae^,^^,^^f.^*^^fall, downfall, ruin, destruction^#^1^#^noun^#^^^', 
'5^%^ruō^,^ru$ere^,^ru$ī^,^rut$us^^*^^fall, go to ruin, rush^#^3^#^verb^#^^^', 
'5^%^sine^,^^,^^,^^^*^^without^#^^#^prep. + abl.^#^^^', 
'5^%^socius^,^soci$a^,^socium^,^^^*^^allied^#^2/1/2^#^adjective^#^^^', 
'5^%^socius^,^soci$ī^,^^,^^m.^*^^ally^#^^#^^#^^^', 
'5^%^tamen^,^^,^^,^^^*^^nevertheless^#^^#^adverb^#^^^', 
'5^%^vīvō^,^vīv$ere^,^vīx$ī^,^vīct$us^^*^^be alive, live^#^3^#^verb^#^^^', 
'5^%^vocō^,^voc$āre^,^vocāv$ī^,^vocāt$us^^*^^call^#^1^#^verb^#^^^', 
'****^%^^,^^,^^,^^^*^^^#^^#^^#^^^', 
'6^%^animal^,^animāl$is^,^-ium^,^^n.^*^^animal^#^3^#^noun^#^^^', 
'6^%^Athēnae^,^Athēn$ārum^,^^,^^f.pl.^*^^Athens^#^1^#^noun^#^^^', 
'6^%^atque^,^^,^^,^^^*^^and^#^^#^coordinating conjunction^#^^^', 
'6^%^ac^,^^,^^,^^^*^^and^#^^#^coordinating conjunction^#^^^', 
'6^%^aurōra^,^aurōr$ae^,^^,^^f.^*^^dawn^#^1^#^noun^#^^^', 
'6^%^careō^,^car$ēre^,^caru$ī^,^carit$us^^*^^lack, be without^#^2^#^verb^#^+ ablative^^', 
'6^%^corpus^,^corpor$is^,^^,^^n.^*^^body^#^3^#^noun^#^^^', 
'6^%^dīcō^,^dīc$ere^,^dīx$ī^,^dict$us^^*^^say, tell , speak^#^3^#^verb^#^^^', 
'6^%^diū^,^^,^^,^^^*^^for a long time^#^^#^adverb^#^^^', 
'6^%^domus^,^dom$ī^,^^,^^f.^*^^house, home^#^^#^^#^^^', 
'6^%^exemplar^,^exemplār$is^,^-ium^,^^n.^*^^copy, model, example^#^^#^^#^^^', 
'6^%^exemplum^,^exempl$ī^,^^,^^n.^*^^example^#^^#^^#^^^', 
'6^%^frāter^,^frātr$is^,^^,^^m.^*^^brother^#^^#^^#^^^', 
'6^%^homō^,^homin$is^,^^,^^m.^*^^human being, man^#^3^#^noun^#^^^', 
'6^%^ignis^,^ign$is^,^-ium^,^^m.^*^^fire^#^3^#^noun^#^^^', 
'6^%^Italia^,^Itali$ae^,^^,^^f.^*^^Italy^#^1^#^noun^#^^^', 
'6^%^Iūnō^,^Iūnōn$is^,^^,^^f.^*^^Juno (sister and wife of Jupiter)^#^^#^^#^^^', 
'6^%^Iuppiter^,^Iov$is^,^^,^^m.^*^^Jupiter (god of the sky)^#^^#^^#^^^', 
'6^%^līberō^,^līber$āre^,^līberāv$ī^,^līberāt$us^^*^^free^#^1^#^verb^#^^^', 
'6^%^lūmen^,^lūmin$is^,^^,^^n.^*^^light^#^3^#^noun^#^^^', 
'6^%^mare^,^mar$is^,^-ium^,^^n.^*^^sea^#^3^#^noun^#^^^', 
'6^%^māter^,^mātr$is^,^^,^^f.^*^^mother^#^3^#^noun^#^^^', 
'6^%^mēns^,^ment$is^,^-ium^,^^f.^*^^mind, disposition, intellect^#^3^#^noun^#^^^', 
'6^%^mīlēs^,^mīlit$is^,^^,^^m.^*^^soldier^#^3^#^noun^#^^^', 
'6^%^moenia^,^moeni$um^,^^,^^n.pl.^*^^(city) walls^#^3^#^noun^#^^^', 
'6^%^mōns^,^mont$is^,^-ium^,^^m.^*^^mountain^#^3^#^noun^#^^^', 
'6^%^nōn sōlum … sed etiam^,^^,^^,^^^*^^not only…but also^#^^#^^#^^^', 
'6^%^nox^,^noct$is^,^-ium^,^^f.^*^^night^#^3^#^noun^#^^^', 
'6^%^oppūgnō^,^oppūgn$āre^,^oppūgnāv$ī^,^oppūgnāt$us^^*^^attack, fight against^#^1^#^verb^#^^^', 
'6^%^pater^,^patr$is^,^^,^^m.^*^^father^#^3^#^noun^#^^^', 
'6^%^regō^,^reg$ere^,^rēx$ī^,^rēct$us^^*^^rule^#^3^#^verb^#^^^', 
'6^%^rēx^,^rēg$is^,^^,^^m.^*^^king^#^3^#^noun^#^^^', 
'6^%^Rōma^,^Rōm$ae^,^^,^^f.^*^^Rome^#^1^#^noun^#^^^', 
'6^%^rūmor^,^rūmōr$is^,^^,^^m.^*^^rumor, gossip^#^3^#^noun^#^^^', 
'6^%^rūs^,^rūr$is^,^^,^^n.^*^^country (as opposed to city)^#^3^#^noun^#^^^', 
'6^%^sānus^,^sān$a^,^sān$um^,^^^*^^sound, healthy, sane^#^2/1/2^#^adjective^#^^^', 
'6^%^sciō^,^sc$īre^,^scīv$ī^,^scīt$us^^*^^know^#^4^#^verb^#^^^', 
'6^%^servitūs^,^servitūt$is^,^^,^^f.^*^^slavery^#^3^#^noun^#^^^', 
'6^%^sīdus^,^sīder$is^,^^,^^n.^*^^constellation, star; heaven^#^3^#^noun^#^^^', 
'6^%^soror^,^sorōr$is^,^^,^^f.^*^^sister^#^3^#^noun^#^^^', 
'6^%^spargō^,^sparg$ere^,^spars$ī^,^spars$us^^*^^scatter, sprinkle, distribute^#^3^#^verb^#^^^', 
'6^%^timor^,^timōr$is^,^^,^^m.^*^^fear, dread^#^3^#^noun^#^^^', 
'6^%^urbs^,^urb$is^,^-ium^,^^f.^*^^city^#^3^#^noun^#^^^', 
'6^%^vigor^,^vigōr$is^,^^,^^m.^*^^liveliness, activity, vigor^#^3^#^noun^#^^^', 
'6^%^vīs^,^pl.=vīr$ēs^,^vīrium^,^^f.^*^^force, power; (pl.=strength)^#^3^#^noun^#^^^', 
'***^%^^,^^,^^,^^^*^^^#^^#^^#^^^', 
'7^%^amō^,^amār$e^,^amāv$ī^,^amāt$us^^*^^love^#^1^#^verb^#^^^', 
'7^%^amor^,^amōr$is^,^^,^^m.^*^^love^#^3^#^noun^#^^^', 
'7^%^annus^,^ann$ī^,^^,^^m.^*^^year^#^3^#^noun^#^^^', 
'7^%^Asia^,^Asi$ae^,^^,^^f.^*^^Asia^#^1^#^noun^#^^^', 
'7^%^auctor ^,^auctōr$is^,^^,^^m.^*^^producer, founder, author^#^3^#^noun^#^^^', 
'7^%^cīvis^,^cīv$is^,^cīvium^,^^m., f.^*^^citizen^#^3^#^noun^#^^^', 
'7^%^cōnficiō^,^cōnfic$ere^,^cōnfēc$ī^,^cōnfect$us^^*^^complete^#^3i^#^verb^#^^^', 
'7^%^ego^,^me$ī^,^^,^^^*^^I^#^^#^pronoun^#^^^', 
'7^%^fīnis^,^fīn$is^,^fīnium^,^^m.^*^^end, boundary, limit^#^3^#^noun^#^^^', 
'7^%^genus^,^gener$is^,^^,^^n.^*^^descent, origin, race, sort^#^3^#^noun^#^^^', 
'7^%^hic^,^haec^,^hoc^,^^^*^^this, the latter^#^^#^adjective^#^^huius/huic/hunc.hanc/hōc/hāc/hī/hōrum/hārum/hīs/hōs/hās/^', 
'7^%^hōra^,^hōr$ae^,^^,^^f.^*^^hour, season^#^1^#^noun^#^^^', 
'7^%^hostis^,^host$is^,^hostium^,^^m.^*^^enemy, public enemy^#^3^#^noun^#^^^', 
'7^%^ille^,^ill$a^,^illud^,^^^*^^that, the former^#^^#^adjective^#^^^', 
'7^%^inveniō^,^inven$īre^,^invēn$ī^,^invent$us^^*^^come upon, discover, find^#^4^#^verb^#^^^', 
'7^%^is^,^ea^,^id^,^^^*^^this, that; he, she, it^#^^#^adjective^#^^eius/eī/eum/eam/eō/eā/eōrum/eārum/eīs/eōs/eās^', 
'7^%^locus^,^loc$ī^,^^,^^m.^*^^place, spot^#^2^#^noun^#^^^', 
'7^%^meus^,^me$a^,^meum^,^^^*^^my, mine, my own^#^2/1/2^#^adjective^#^^^', 
'7^%^mors^,^mort$is^,^mortium^,^^f.^*^^death^#^3^#^noun^#^^^', 
'7^%^noster^,^nostr$a^,^nostr$um^,^^^*^^our, ours, our own^#^2/1/2^#^adjective^#^^^', 
'7^%^ōdī^,^ōd$isse^,^^,^^^*^^hate^#^(irreg.)^#^verb^#^defective verb; has only perfect forms, with present meanings^^', 
'7^%^opus^,^oper$is^,^^,^^n.^*^^work^#^3^#^noun^#^^^', 
'7^%^opus est^,^^,^^,^^^*^^there is need of^#^^#^idiom^#^+ nom. or abl. (instrumental) of thing needed; less frequently, + gen. ; dat. of person who has the need.^^', 
'7^%^perficiō^,^perfic$ere^,^perfēc$ī^,^perfect$us^^*^^accomplish, complete, finish^#^3i^#^verb^#^^^', 
'7^%^pēs^,^ped$is^,^^,^^m.^*^^foot^#^3^#^noun^#^^^', 
'7^%^placeō^,^plac$ēre^,^placu$ī^,^placit$us^^*^^be pleasing to, please^#^2^#^verb^#^+ dat.^^', 
'7^%^premō^,^prem$ere^,^press$ī^,^press$us^^*^^press, press upon, press hard^#^3^#^verb^#^^^', 
'7^%^opprimō^,^opprim$ere^,^oppress$ī^,^oppress$us^^*^^press upon, overwhelm, suppress, oppress^#^3^#^verb^#^^^', 
'7^%^quī^,^quae^,^quod^,^^^*^^who, which, that^#^^#^pronoun^#^^^', 
'7^%^quī^,^quae^,^quod^,^^^*^^which, what^#^^#^adjective^#^^^', 
'7^%^quīnque^,^^,^^,^^^*^^five^#^^#^adjective^#^indeclinable^^', 
'7^%^quis^,^quid^,^^,^^^*^^who, what^#^^#^pronoun^#^^^', 
'7^%^salūs^,^salūt$is^,^^,^^f.^*^^health, safety^#^3^#^noun^#^^^', 
'7^%^salūtem dicere^,^^,^^,^^^*^^say hello, greet^#^^#^idiom^#^^^', 
'7^%^spēro^,^spēr$āre^,^spērāv$ī^,^spērāt$us^^*^^hope (for)^#^1^#^verb^#^^^', 
'7^%^--^,^su$ī^,^^,^^^*^^himself, herself, itself, themselves^#^^#^pronoun^#^will not be found in nominative^^', 
'7^%^suus^,^su$a^,^suum^,^^^*^^his/her/its/their own^#^2/1/2^#^adjective^#^^^', 
'7^%^tempus^,^tempor$is^,^^,^^n.^*^^time, period, season^#^3^#^noun^#^^^', 
'7^%^tū^,^tu$ī^,^^,^^^*^^you^#^^#^pronoun^#^^^', 
'7^%^tuus^,^tu$a^,^tuum^,^^^*^^your, yours, your own (sing.)^#^2/1/2^#^adjective^#^^^', 
'7^%^vester^,^vestr$a^,^vestum^,^^^*^^your, yours, your own (pl.)^#^2/1/2^#^adjective^#^^^', 
'7^%^vōx^,^vōc$is^,^^,^^f.^*^^voice^#^3^#^noun^#^^^', 
'***^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'8^%^ācer^,^ācr$is^,^ācre^,^^^*^^sharp, keen, fierce^#^3^#^adjective^#^^^', 
'8^%^Carmen^,^carmin$is^,^^,^^n.^*^^song, poem, incantation^#^3^#^noun^#^^^', 
'8^%^cīvitās^,^cīvitāt$is^,^^,^^f.^*^^citizenship; state^#^3^#^noun^#^^^', 
'8^%^diēs^,^di$ēī^,^^,^^m.^*^^day^#^5^#^noun^#^^^', 
'8^%^domus^,^dom$ūs or domī^,^^,^^f.^*^^house, home^#^2, 4^#^noun^#^most common forms are a mix of 2nd and 4th declension^^', 
'8^%^dulcis^,^dulc$e^,^^,^^^*^^sweet, pleasant^#^3^#^adjective^#^^^', 
'8^%^eō^,^īre^,^iī or īvī^,^it$us^^*^^go^#^4^#^verb^#^^^', 
'8^%^fēlīx^,^fēlīc$is^,^^,^^^*^^happy, fortunate^#^3^#^adjective^#^^^', 
'8^%^īnfēlīx^,^īnfēlīc$is^,^^,^^^*^^unhappy, unfortunate^#^3^#^adjective^#^^^', 
'8^%^fidēs^,^fid$eī^,^^,^^f.^*^^faith, trust, trustworthiness^#^5^#^noun^#^^^', 
'8^%^fortis^,^fort$e^,^^,^^^*^^strong, brave^#^3^#^adjective^#^^^', 
'8^%^frīgidus^,^frīgid$a^,^frīgid$um^,^^^*^^cold^#^2/1/2^#^adjective^#^^^', 
'8^%^frūctus^,^frūct$ūs^,^^,^^m.^*^^enjoyment, fruit, profit^#^4^#^noun^#^^^', 
'8^%^frūctuī esse^,^^,^^,^^^*^^to be a profit, be an asset to^#^^#^idiom^#^+ dat.^^', 
'8^%^fulgeō^,^fulg$ēre^,^fuls$ī^,^--^^*^^flash, shine^#^2^#^verb^#^^^', 
'8^%^gravis^,^grav$e^,^^,^^^*^^heavy, severe, important^#^3^#^adjective^#^^^', 
'8^%^iaciō^,^iac$ere^,^iēc$ī^,^iact$us^^*^^throw^#^3i^#^verb^#^^^', 
'8^%^iactō^,^iact$āre^,^iactāv$ī^,^iactāt$us^^*^^throw, scatter, shake; boast^#^3i^#^verb^#^^^', 
'8^%^ingēns^,^ingent$is^,^^,^^^*^^huge^#^3^#^adjective^#^^^', 
'8^%^īra^,^īr$ae^,^^,^^f.^*^^wrath, anger^#^1^#^noun^#^^^', 
'8^%^iubeō^,^iub$ēre^,^iuss$ī^,^iuss$us^^*^^order, command^#^2^#^verb^#^+ inf., not ut clause^^', 
'8^%^lībertās^,^lībertāt$is^,^^,^^f.^*^^freedom^#^3^#^noun^#^^^', 
'8^%^lītus^,^lītor$is^,^^,^^n.^*^^shore, beach^#^3^#^noun^#^^^', 
'8^%^longus^,^long$a^,^longum^,^^^*^^long^#^2/1/2^#^adjective^#^^^', 
'8^%^longē^,^^,^^,^^^*^^far off, at a distance,  far and wide^#^^#^adverb^#^^^', 
'8^%^lūx^,^lūc$is^,^^,^^f.^*^^light^#^3^#^noun^#^^^', 
'8^%^prīma lūce^,^^,^^,^^^*^^at the first light, at daybreak^#^^#^idiom^#^^^', 
'8^%^manus^,^man$ūs^,^^,^^f.^*^^hand; band, troop^#^4^#^noun^#^^^', 
'8^%^memor^,^memor$is^,^^,^^^*^^mindful, remembering^#^3^#^adjective^#^+ gen.^^', 
'8^%^metus^,^met$ūs^,^^,^^m.^*^^fear, dread^#^4^#^noun^#^^^', 
'8^%^mōtus^,^mōt$ūs^,^^,^^m.^*^^motion, movement^#^4^#^noun^#^^^', 
'8^%^nōmen^,^nōmin$is^,^^,^^n.^*^^name^#^3^#^noun^#^^^', 
'8^%^nūmen^,^nūmin$is^,^^,^^n.^*^^divinity, divine spirit^#^3^#^noun^#^^^', 
'8^%^ob^,^^,^^,^^^*^^on account of^#^^#^preposition^#^+ acc.^^', 
'8^%^quam ob rem^,^^,^^,^^^*^^on account of which, why^#^^#^^#^^^', 
'8^%^omnis^,^omn$e^,^^,^^^*^^every, all^#^3^#^adjective^#^^^', 
'8^%^opīniō^,^opiniōn$is^,^^,^^f.^*^^opinion^#^3^#^noun^#^^^', 
'8^%^pectus^,^pector$is^,^^,^^n.^*^^heart, breast^#^3^#^noun^#^^^', 
'8^%^prō^,^^,^^,^^^*^^in front of, for, on behalf of, instead of, in return for^#^^#^preposition^#^+ abl.^^', 
'8^%^profugus^,^profug$a^,^profugum^,^^^*^^fugitive, banished, exiled^#^2/1/2^#^adjective^#^^^', 
'8^%^pūblicus^,^pūblic$a^,^pūblicum^,^^^*^^public^#^2/1/2^#^adjective^#^^^', 
'8^%^quaerō^,^quaer$ere^,^quaesīv$ī^,^quaesīt$us^^*^^look for, search for, seek, ask^#^^#^^#^^^', 
'8^%^rēs^,^re$ī^,^^,^^f.^*^^thing, matter, affair, situation^#^5^#^noun^#^^^', 
'8^%^rēs pūblica^,^^,^^,^^^*^^state, republic^#^^#^idiom^#^^^', 
'8^%^saevus^,^saev$a^,^saevum^,^^^*^^cruel^#^2/1/2^#^adjective^#^^^', 
'8^%^sēnsus^,^sēns$ūs^,^^,^^m.^*^^sensation, feeling^#^4^#^noun^#^^^', 
'8^%^species^,^speci$ēī^,^^,^^f.^*^^appearance^#^5^#^noun^#^^^', 
'8^%^spēs^,^spe$ī^,^^,^^f.^*^^hope^#^5^#^noun^#^^^', 
'8^%^superus^,^super$a^,^superum^,^^^*^^above, upper^#^2/1/2^#^adjective^#^^^', 
'8^%^superī^,^super$ōrum^,^^,^^m. pl.^*^^the gods above^#^^#^^#^^^', 
'8^%^vertex^,^vertic$is^,^^,^^m.^*^^head, top, summit; whirlpool, whirlwind^#^3^#^noun^#^^^', 
'***^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'9^%^aiō^,^^,^^,^^^*^^say, affirm^#^(irreg.)^#^verb^#^defective verb: ^^', 
'9^%^amīcitia^,^amīciti$ae^,^^,^^f.^*^^friendship^#^1^#^noun^#^^^', 
'9^%^cadō^,^cad$ere^,^cecid$ī^,^cās$us^^*^^fall^#^3^#^verb^#^^^', 
'9^%^cāsus^,^cās$ūs^,^^,^^m.^*^^fall, accident, occurrence, chance^#^4^#^noun^#^^^', 
'9^%^cōnsilium^,^cōnsili$ī^,^^,^^n.^*^^counsel, plan, advice^#^2^#^noun^#^^^', 
'9^%^crūdēlis^,^crūdēl$e^,^^,^^^*^^cruel^#^3^#^adjective^#^^^', 
'9^%^dēmēns^,^dēment$is^,^^,^^^*^^mad, raving^#^3^#^adjective^#^^^', 
'9^%^facilis^,^facil$e^,^^,^^^*^^easy^#^3^#^adjective^#^^^', 
'9^%^facile^,^^,^^,^^^*^^easily^#^^#^adverb^#^^^', 
'9^%^difficilis^,^difficil$e^,^^,^^^*^^difficult^#^3^#^adjective^#^^^', 
'9^%^gracilis^,^gracil$e^,^^,^^^*^^slender, unadorned, simple^#^3^#^adjective^#^^^', 
'9^%^hospes^,^hospit$is^,^^,^^m.^*^^guest, host^#^3^#^noun^#^^^', 
'9^%^humilis^,^humil$e^,^^,^^^*^^humble, lowly^#^3^#^adjective^#^^^', 
'9^%^laudō^,^laud$āre^,^laudāv$ī^,^laudāt$us^^*^^praise^#^1^#^verb^#^^^', 
'9^%^laus^,^laud$is^,^^,^^f.^*^^praise^#^3^#^noun^#^^^', 
'9^%^magnopere^,^^,^^,^^^*^^greatly^#^^#^adverb^#^^^', 
'9^%^maiōrēs^,^maiōr$um^,^^,^^m.pl.^*^^ancestors^#^3^#^noun^#^^^', 
'9^%^male^,^^,^^,^^^*^^badly^#^^#^adverb^#^^^', 
'9^%^Mārs^,^Mārt$is^,^^,^^m.^*^^Mars (god of war)^#^3^#^noun^#^^^', 
'9^%^multum^,^^,^^,^^^*^^much, very^#^^#^adverb^#^^^', 
'9^%^mūnio^,^mūn$īre^,^mūnīv$ī^,^mūnīt$us^^*^^fortify^#^4^#^verb^#^^^', 
'9^%^nam^,^^,^^,^^^*^^for^#^^#^conjunction^#^^^', 
'9^%^odium^,^od$iī^,^^,^^n.^*^^hate^#^2^#^noun^#^^^', 
'9^%^parum^,^^,^^,^^^*^^too little, not enough^#^^#^adverb, adjective^#^^^', 
'9^%^parvus^,^parv$a^,^parvum^,^^^*^^little, small^#^2/1/2^#^adjective^#^^^', 
'9^%^prius^,^^,^^,^^^*^^before, previously^#^^#^adverb^#^^^', 
'9^%^quam prīmum^,^^,^^,^^^*^^as  soon as possible^#^^#^phrase^#^^^', 
'9^%^proximus^,^proxim$a^,^proximum^,^^^*^^nearest, next^#^2/1/2^#^adjective^#^^^', 
'9^%^quam^,^^,^^,^^^*^^than (used in comparisons)^#^^#^subordinating conjunction^#^^^', 
'9^%^saepe^,^^,^^,^^^*^^often^#^^#^adverb^#^^^', 
'9^%^sapiens^,^sapient$is^,^^,^^^*^^wise^#^3^#^adjective^#^^^', 
'9^%^sapientia^,^sapienti$ae^,^^,^^f.^*^^wisdom^#^1^#^noun^#^^^', 
'9^%^satis^,^^,^^,^^^*^^enough^#^^#^adverb, adjective^#^^^', 
'9^%^serēnus^,^serēn$a^,^serēnum^,^^^*^^serene, calm^#^2/1/2^#^adjective^#^^^', 
'9^%^similis^,^simil$e^,^^,^^^*^^like, similar (to)^#^3^#^adjective^#^+ gen. or dat.^^', 
'9^%^dissimilis^,^dissimil$e^,^^,^^^*^^dissimilar, unlike^#^3^#^adjective^#^+ gen. or dat.^^', 
'9^%^solvō^,^solv$ere^,^solv$ī^,^solūt$us^^*^^loosen, free, untie^#^3^#^verb^#^^^', 
'9^%^summus^,^summ$a^,^summum^,^^^*^^highest, top (of)^#^2/1/2^#^adjective^#^^^', 
'9^%^supplex^,^supplici$s^,^^,^^^*^^suppliant, humble^#^3^#^adjective^#^^^', 
'9^%^tam^,^^,^^,^^^*^^so^#^^#^adverb^#^^^', 
'9^%^tam … quam^,^^,^^,^^^*^^so … as, as … as^#^^#^relative/correlative^#^^^', 
'9^%^templum^,^templ$ī^,^^,^^n.^*^^temple^#^2^#^noun^#^^^', 
'9^%^tūtus^,^tūt$a^,^tūtum^,^^^*^^safe^#^2/1/2^#^adjective^#^^^', 
'**^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'10^%^alius^,^ali$a^,^aliud^,^^^*^^other, another^#^2/1/2^#^adjective^#^^^', 
'10^%^alius…alius^,^^,^^,^^^*^^one…another^#^^#^phrase^#^^^', 
'10^%^aliī…aliī^,^^,^^,^^^*^^some…others^#^^#^phrase^#^^^', 
'10^%^alter^,^alter$a^,^alterum^,^^^*^^the other (of two)^#^2/1/2^#^adjective^#^^^', 
'10^%^apud^,^^,^^,^^^*^^at, near, among; at the house of^#^^#^preposition^#^+ acc.^^', 
'10^%^ars^,^art$is^,^atrium^,^^f.^*^^skill, art^#^3^#^noun^#^^^', 
'10^%^audācia^,^audāci$ae^,^^,^^f.^*^^boldness, courage^#^1^#^noun^#^^^', 
'10^%^audāx^,^audāc$is^,^^,^^^*^^bold, courageous^#^3^#^adjective^#^^^', 
'10^%^auxilium^,^auxili$ī^,^^,^^n.^*^^aid^#^2^#^noun^#^^^', 
'10^%^certus^,^cert$a^,^certum^,^^^*^^certain, sure^#^2/1/2^#^adjective^#^^^', 
'10^%^incertus^,^incert$a^,^incertum^,^^^*^^uncertain, unsure^#^2/1/2^#^adjective^#^^^', 
'10^%^coepī^,^coep$isse^,^coept$us^,^^^*^^began^#^^#^verb^#^defective; occurs only in perfect system^^', 
'10^%^custōs^,^custōd$is^,^^,^^m.^*^^guardian^#^3^#^noun^#^^^', 
'10^%^doceō^,^doc$ēre^,^docu$ī^,^doct$us^^*^^teach^#^2^#^verb^#^^^', 
'10^%^errō^,^err$āre^,^errāv$ī^,^errāt$us^^*^^wander, err^#^1^#^verb^#^^^', 
'10^%^ferō^,^fer$re^,^tul$ī^,^lāt$us^^*^^bring, carry, bear, endure^#^^#^verb^#^irregular conjugation in present system^^', 
'10^%^figūra^,^figūr$ae^,^^,^^f.^*^^figure, form, shape^#^1^#^noun^#^^^', 
'10^%^foedus^,^foeder$is^,^^,^^n.^*^^pact, treaty, agreement^#^3^#^noun^#^^^', 
'10^%^fugiō^,^fug$ere^,^fūg$ī^,^fugit$us^^*^^flee^#^3i^#^verb^#^^^', 
'10^%^fuga^,^fug$ae^,^^,^^f.^*^^flight^#^1^#^noun^#^^^', 
'10^%^gaudium^,^gaudi$ī^,^^,^^n.^*^^joy^#^2^#^noun^#^^^', 
'10^%^gēns^,^gent$is^,^gentium^,^^f.^*^^race, people^#^3^#^noun^#^^^', 
'10^%^iam^,^^,^^,^^^*^^now, by this time, already, soon^#^^#^adverb^#^^^', 
'10^%^iter^,^itiner$is^,^^,^^n.^*^^journey, route^#^3^#^noun^#^^^', 
'10^%^iungō^,^iung$ere^,^iūnx$ī^,^iūnct$us^^*^^join^#^3^#^verb^#^^^', 
'10^%^coniūnx^,^coniug$is^,^^,^^m., f.^*^^husband, wife, spouse^#^3^#^noun^#^^^', 
'10^%^mōs^,^mōr$is^,^^,^^m.^*^^custom; in pl., character^#^3^#^noun^#^^^', 
'10^%^negō^,^neg$āre^,^negāv$ī^,^negat$us^^*^^deny, say no^#^1^#^verb^#^^^', 
'10^%^neuter^,^neutr$a^,^neutrum^,^^^*^^neither^#^2/1/2^#^adjective^#^^^', 
'10^%^nūllus^,^nūll$a^,^nūllum^,^^^*^^no, none^#^2/1/2^#^adjective^#^^^', 
'10^%^orbis^,^orb$is^,^orbium^,^^m.^*^^ring, orb, circle^#^3^#^noun^#^^^', 
'10^%^orbis terrarium^,^^,^^,^^^*^^circle of lands; the world^#^^#^idiom^#^^^', 
'10^%^pars^,^part$is^,^partium^,^^f.^*^^part^#^3^#^noun^#^^^', 
'10^%^propter^,^^,^^,^^^*^^on account of, because^#^^#^preposition^#^+ acc.^^', 
'10^%^quantus^,^quant$a^,^quantum^,^^^*^^how much, how great^#^2/1/2^#^adjective, interrogative adjective^#^^^', 
'10^%^quot^,^^,^^,^^^*^^how many^#^^#^adjective^#^indeclinable^^', 
'10^%^signum^,^sign$ī^,^^,^^n.^*^^signal, sign^#^2^#^noun^#^^^', 
'10^%^sōl^,^sōl$is^,^^,^^m.^*^^sun^#^3^#^noun^#^^^', 
'10^%^sōlus^,^sōl$a^,^sōlum^,^^^*^^alone, only^#^2/1/2^#^adjective^#^^^', 
'10^%^tantus^,^tant$a^,^tantum^,^^^*^^so much, so great^#^2/1/2^#^adjective^#^^^', 
'10^%^tantus…quantus, quantus…tantus^,^^,^^,^^^*^^as (so) much…as; as (so) great…as^#^^#^relative/correlative^#^^^', 
'10^%^temptō^,^tempt$āre^,^temptāv$ī^,^temptāt$us^^*^^try, attempt^#^1^#^verb^#^^^', 
'10^%^tot^,^^,^^,^^^*^^so many^#^^#^adjective^#^indeclinable^^', 
'10^%^tot…quot, quot…tot^,^^,^^,^^^*^^as many…as^#^^#^relative/correlative^#^^^', 
'10^%^tōtus^,^tōt$a^,^tōtum^,^^^*^^all, whole^#^2/1/2^#^adjective^#^^^', 
'10^%^ūllus^,^ūll$a^,^ūllum^,^^^*^^any^#^2/1/2^#^adjective^#^^^', 
'10^%^ūnus^,^ūn$a^,^ūnum^,^^^*^^one, alone^#^2/1/2^#^adjective^#^^^', 
'10^%^uter^,^utr$a^,^utrum^,^^^*^^which (of two)^#^2/1/2^#^adjective^#^^^', 
'10^%^virtūs^,^virtūt$is^,^^,^^f.^*^^manliness, courage, excellence, virtue^#^3^#^noun^#^^^', 
'^^^^^^^^^^^^^^^^^^^^', 
'11^%^arbitror^,^arbitr$ārī^,^arbitrāt$us sum^,^^^*^^think, believe, judge^#^1^#^verb^#^deponent^^', 
'11^%^audeō^,^aud$ēre^,^aus$us sum^,^^^*^^dare^#^2^#^verb^#^partial deponent; + infinitive^^', 
'11^%^cēna^,^cēn$ae^,^^,^^f.^*^^dinner^#^1^#^noun^#^^^', 
'11^%^cōnor^,^cōn$ārī^,^cōnāt$us sum^,^^^*^^try, attempt^#^1^#^verb^#^deponent^^', 
'11^%^cōnsul^,^cōnsul$is^,^^,^^m.^*^^consul^#^3^#^noun^#^^^', 
'11^%^crēdō^,^crēd$ere^,^crēdid$i^,^crēdit$us^^*^^be credulous, believe; be trusting, trust (+ dat.)^#^3^#^verb^#^^^', 
'11^%^cupidus^,^cupid$a^,^cupidum^,^^^*^^desirous, eager, fond of (+ gen.)^#^2/1/2^#^adjective^#^^^', 
'11^%^dīvitiae^,^dīviti$ārum^,^^,^^f. pl.^*^^riches, wealth (pl. only)^#^1^#^noun^#^^^', 
'11^%^dux^,^duc$is^,^^,^^m., f.^*^^leader, guide^#^3^#^noun^#^^^', 
'11^%^experior^,^exper$īrī^,^expert$us sum^,^^^*^^try, put to the test,  experience^#^4^#^verb^#^deponent^^', 
'11^%^familia^,^famili$ae^,^^,^^f.^*^^family, household^#^1^#^noun^#^^^', 
'11^%^fateor^,^fat$ērī^,^fass$us sum^,^^^*^^confess^#^2^#^verb^#^deponent^^', 
'11^%^cōnfiteor^,^cōnfit$ērī^,^cōnfess$us sum^,^^^*^^confess^#^2^#^verb^#^deponent^^', 
'11^%^flūmen^,^flūmin$is^,^^,^^n.^*^^river, running water^#^3^#^noun^#^^^', 
'11^%^forum^,^for$ī^,^^,^^n.^*^^open space, market place, public square^#^2^#^noun^#^^^', 
'11^%^gradior^,^grad$ī^,^gress$us sum^,^^^*^^step, walk^#^3^#^verb^#^deponent^^', 
'11^%^aggredior^,^aggred$ī^,^aggress$us sum^,^^^*^^go to, approach^#^3^#^verb^#^deponent; compound, ad + gradior^^', 
'11^%^ēgredior^,^ēgred$ī^,^ēgress$us sum^,^^^*^^go out, go away^#^3^#^verb^#^deponent; compound^^', 
'11^%^ingredior^,^ingred$ī^,^ingress$us sum^,^^^*^^go into, enter, advance, begin^#^3^#^verb^#^deponent; compound^^', 
'11^%^prōgredior^,^prōgred$ī^,^prōgress$us sum^,^^^*^^go forth, advance, proceed^#^3^#^verb^#^deponent; compound^^', 
'11^%^hortor^,^hort$ārī^,^hortāt$us sum^,^^^*^^urge, encourage^#^2^#^verb^#^+ ut/nē and subjunctive in indirect command^^', 
'11^%^imperātor^,^imperātōr$is^,^^,^^m.^*^^commander, general^#^3^#^noun^#^^^', 
'11^%^iuvenis^,^iuven$is^,^^,^^m., f.^*^^youth, young person^#^3^#^noun^#^^^', 
'11^%^loquor^,^loqu$ī^,^locūt$us sum^,^^^*^^speak, talk^#^3^#^verb^#^deponent^^', 
'11^%^mālō^,^māl$le^,^māl$uī^,^--^^*^^prefer, chose rather^#^^#^verb^#^irregular in present system^^', 
'11^%^minor^,^min$ārī^,^mināt$us sum^,^^^*^^jut forth, threaten^#^1^#^verb^#^deponent^^', 
'11^%^morior^,^mor$ī^,^mortu$us sum^,^^^*^^die^#^3^#^verb^#^deponent^^', 
'11^%^nāscor^,^nāsc$ī^,^nāt$us sum^,^^^*^^be born, descend from^#^3^#^verb^#^deponent^^', 
'11^%^nāvis^,^nāv$is^,^nāvium^,^^f.^*^^ship^#^3^#^noun^#^^^', 
'11^%^neglegō^,^negleg$ere^,^neglēx$ī^,^neglēct$us^^*^^disregard, neglect^#^3^#^verb^#^compound^^', 
'11^%^nōlō^,^nōl$le^,^nōlu$ī^,^--^^*^^be unwilling, wish…not^#^^#^verb^#^irregular in present system^^', 
'11^%^ōrātor^,^ōrātōr$is^,^^,^^m.^*^^speaker^#^3^#^noun^#^^^', 
'11^%^parēns^,^parent$is^,^^,^^m., f.^*^^parent^#^3 ^#^noun ^#^^^', 
'11^%^patior^,^pat$ī^,^pass$us sum^,^^^*^^suffer, endure, allow^#^3^#^verb^#^deponent^^', 
'11^%^pauper^,^pauper$is^,^^,^^^*^^poor^#^3^#^adjective^#^^^', 
'11^%^praemium^,^praemi$ī^,^^,^^n.^*^^reward^#^2^#^noun^#^^^', 
'11^%^precor^,^prec$ārī^,^precāt$us sum^,^^^*^^beg, request^#^3^#^verb^#^deponent^^', 
'11^%^proficīscor^,^proficīsc$ī^,^profect$us sum^,^^^*^^set forth, set out, start^#^3^#^verb^#^deponent^^', 
'11^%^scelus^,^sceler$is^,^^,^^n.^*^^wicked deed, crime^#^3^#^noun^#^^^', 
'11^%^sequor^,^sequ$ī^,^secūt$us sum^,^^^*^^follow^#^3^#^verb^#^deponent^^', 
'11^%^servō^,^serv$āre^,^servāv$ī^,^servāt$us^^*^^save, preserve, rescue, keep^#^1^#^verb^#^NOT “serve” !^^', 
'11^%^soleō^,^sol$ēre^,^solit$us sum^,^^^*^^be accustomed, be customary^#^2^#^verb^#^deponent; often + inf.^^', 
'11^%^statua^,^statu$ae^,^^,^^f.^*^^statue^#^1^#^noun^#^^^', 
'11^%^ut^,^^,^^,^^^*^^as, when^#^^#^subordinating conjunction^#^+ indicative^^', 
'11^%^ūtor^,^ūt$ī^,^ūs$us sum^,^^^*^^use, enjoy, experience^#^3^#^verb^#^+ abl. ; deponent^^', 
'11^%^vereor^,^ver$ērī^,^verit$us sum^,^^^*^^reverence, fear, dread^#^2^#^verb^#^deponent; + clause of fearing^^', 
'11^%^volō^,^vell$e^,^volu$ī^,^--^^*^^wish, want, be willing^#^^#^verb^#^irregular in present system^^', 
'^^^^^^^^^^^^^^^^^^^^', 
'12^%^accipiō^,^accip$ere^,^accēp$ī^,^accept$us^^*^^receive, accept; hear^#^3i^#^verb^#^^^', 
'12^%^recipiō^,^recip$ere^,^recēp$ī^,^recept$us^^*^^take back, regain, recover^#^3i^#^verb^#^^^', 
'12^%^sē recipere^,^^,^^,^^^*^^withdraw, take oneself^#^^#^^#^phrase^^', 
'12^%^an^,^^,^^,^^^*^^or (introducing 2nd part of a double question); whether (introducing single indirect question)^#^^#^conjunction^#^^^', 
'12^%^aura^,^aur$ae^,^^,^^f.^*^^breeze, wind, air^#^1^#^noun^#^^^', 
'12^%^comes^,^comit$is^,^^,^^m., f.^*^^companion^#^3^#^noun^#^^^', 
'12^%^cōpia^,^cōpi$ae^,^^,^^f.^*^^abundance, supply; pl., troops^#^1^#^noun^#^^^', 
'12^%^cūr^,^^,^^,^^^*^^why, for what reason^#^^#^adverb^#^^^', 
'12^%^dēligō^,^dēlig$ere^,^dēlēg$ī^,^dēlēct$us^^*^^select, choose, gather^#^3^#^verb^#^^^', 
'12^%^exorior^,^exor$īrī^,^exort$us sum^,^^^*^^rise,  arise, appear, start^#^4^#^verb^#^deponent^^', 
'12^%^expōnō^,^expōn$ere^,^exposu$ī^,^exposit$us^^*^^set forth, explain, expose^#^3^#^verb^#^compound^^', 
'12^%^horridus^,^horrid$a^,^horridum^,^^^*^^horrible, rough^#^2/1/2^#^adjective^#^^^', 
'12^%^hostīlis^,^hostīl$e^,^^,^^^*^^of an enemy, hostile^#^3^#^adjective^#^^^', 
'12^%^ibi^,^^,^^,^^^*^^there, then^#^^#^demonstrative adverb; adverb^#^^^', 
'12^%^īdem^,^eadem^,^idem^,^^^*^^same^#^^#^adjective^#^irregular^^', 
'12^%^immortālis^,^immortāl$e^,^^,^^^*^^immortal, everlasting^#^3^#^adjective^#^^^', 
'12^%^ipse^,^ips$a^,^ipsum^,^^^*^^self, very^#^^#^adjective^#^irregular^^', 
'12^%^iste^,^ist$a^,^istud^,^^^*^^that (of yours), that damn (of yours), that (with pejorative sense)^#^^#^adjective^#^irregular^^', 
'12^%^iussum^,^iuss$ī^,^^,^^n.^*^^command, order^#^2^#^noun^#^abl. sg. iussū^^', 
'12^%^maneō^,^man$ēre^,^māns$ī^,^māns$us^^*^^remain^#^2^#^verb^#^^^', 
'12^%^remaneō^,^reman$ēre^,^remāns$ī^,^remāns$us^^*^^remain^#^2^#^verb^#^^^', 
'12^%^misereor^,^mis$ērī^,^miserit$us sum^,^^^*^^pity^#^2^#^verb^#^+ gen. ; deponent^^', 
'12^%^modus^,^mod$ī^,^^,^^m.^*^^way, manner, limit; kind^#^2^#^noun^#^^^', 
'12^%^quō modō^,^^,^^,^^^*^^in what way; how^#^^#^adverbial phrase^#^^^', 
'12^%^necne^,^^,^^,^^^*^^or not (generally in second part of double indirect question)^#^^#^conjunction^#^when = an nōn in the indirect question^^', 
'12^%^nesciō^,^nesc$īre^,^nescīv$ī/nesci$ī^,^nescīt$us^^*^^not know, be ignorant^#^4^#^verb^#^^^', 
'12^%^nōnne^,^^,^^,^^^*^^in a direct question, anticipates the answer “yes”^#^^#^adverb^#^^^', 
'12^%^num^,^^,^^,^^^*^^in a direct question, anticipates the answer “no”; in an indirect question, “whether”^#^^#^adverb^#^^^', 
'12^%^occultē^,^^,^^,^^^*^^secretly^#^^#^adverb^#^^^', 
'12^%^ops^,^op$is^,^^,^^f.^*^^power, strength; pl., resources, wealth^#^3^#^noun^#^^^', 
'12^%^paucī^,^pauc$ae^,^pauca^,^^^*^^few^#^2/1/2^#^adjective^#^only in pl.^^', 
'12^%^poscō^,^posc$ere^,^poposc$ī^,^--^^*^^beg, demand^#^3^#^verb^#^^^', 
'12^%^quamdiū^,^^,^^,^^^*^^how long^#^^#^adverb^#^^^', 
'12^%^quandō^,^^,^^,^^^*^^when; since^#^^#^conjunction, adverb^#^^^', 
'12^%^quārē^,^^,^^,^^^*^^why, by what means; and therefore^#^^#^adverb^#^^^', 
'12^%^quia^,^^,^^,^^^*^^because^#^^#^subordinating conjunction^#^^^', 
'12^%^quīdam^,^quaedam^,^quoddam^,^^^*^^certain^#^^#^adjective^#^irregular^^', 
'12^%^quīdam^,^quaedam^,^quiddam^,^^^*^^a certain one, a certain thing^#^^#^pronoun^#^irregular^^', 
'12^%^rogō^,^rog$āre^,^rogāv$ī^,^rogāt$us^^*^^ask (for)^#^1^#^verb^#^^^', 
'12^%^sors^,^sort$is^,^sortium^,^^f.^*^^lot, destiny^#^3^#^noun^#^^^', 
'12^%^tamquam^,^^,^^,^^^*^^as if, as, as it were^#^^#^adverb^#^^^', 
'12^%^tandem^,^^,^^,^^^*^^at last, at length^#^^#^adverb^#^^^', 
'12^%^ubi^,^^,^^,^^^*^^where, when^#^^#^relative adverb^#^^^', 
'12^%^unde^,^^,^^,^^^*^^from where^#^^#^relative adverb^#^^^', 
'12^%^utinam^,^^,^^,^^^*^^I wish!, would that!, if only!^#^^#^adverb^#^can introduce subjunctives of wish^^', 
'12^%^utrum^,^^,^^,^^^*^^whether^#^^#^subordinating conjunction^#^^^', 
'12^%^utrum…an, -ne…an, --…an^,^^,^^,^^^*^^whether…or^#^^#^phrase^#^^^', 
'12^%^utrum…an nōn, -ne…an nōn, --…an nōn^,^^,^^,^^^*^^whether…or not (in direct double questions)^#^^#^phrase^#^^^', 
'13^%^admīrātiō^,^admīrātiōnis^,^^,^^f.^*^^admiration^#^3^#^noun^#^^^', 
'13^%^adulēscēns^,^adulēscentis^,^^,^^^*^^young, youthful^#^3^#^adjective^#^^^', 
'13^%^aliquis^,^aliquid^,^^,^^^*^^someone, something; anyone, anything^#^^#^pronoun^#^^^', 
'13^%^aliquī^,^aliqua^,^aliquod^,^^^*^^some, any^#^^#^adjective^#^irregular^^', 
'13^%^celer^,^celeris^,^celere^,^^^*^^swift^#^3^#^adjective^#^^^', 
'13^%^cōnstituō^,^cōnstituere^,^cōnstituī^,^cōnstitūtus^^*^^set, establish, decide^#^3^#^verb^#^^^', 
'13^%^currō^,^currere^,^cucurrī^,^cursus^^*^^run^#^3^#^verb^#^^^', 
'13^%^duo^,^duae^,^duo^,^^^*^^two^#^^#^adjective^#^irregular^^', 
'13^%^faveō^,^favēre^,^fāvī^,^fautus^^*^^be favorable, favor (+ dat.)^#^2^#^verb^#^^^', 
'13^%^fīō^,^fi$erī^,^fact$us sum^,^^^*^^be made, be done, happen, become^#^^#^verb^#^deponent; serves as pasive of faciō^^', 
'13^%^heri^,^^,^^,^^^*^^yesterday^#^^#^adverb^#^^^', 
'13^%^hīc^,^^,^^,^^^*^^here^#^^#^adverb^#^^^', 
'13^%^īgnōscō^,^īgnōsc$ere^,^īgnōv$ī^,^īgnōt$us^^*^^be forgiving, forgive, pardon (+ dat.)^#^3^#^verb^#^^^', 
'13^%^illīc^,^^,^^,^^^*^^there^#^^#^adverb^#^^^', 
'13^%^īrātus^,^īrāt$a^,^īrāt$um^,^^^*^^angry^#^2/1/2^#^adjective^#^^^', 
'13^%^iūs^,^iūr$is^,^^,^^n.^*^^right, law^#^3^#^noun^#^^^', 
'13^%^lēgātus^,^lēgāt$ī^,^^,^^m.^*^^legate, envoy^#^2^#^noun^#^^^', 
'13^%^mīror^,^mīr$ārī^,^mīrāt$us sum^,^^^*^^wonder (at), be amazed (at), admire^#^1^#^verb^#^deponent^^', 
'13^%^moror^,^mor$ārī^,^morāt$us sum^,^^^*^^delay, stay, hinder^#^1^#^verb^#^^^', 
'13^%^nēmō^,^nēmin$is^,^^,^^m., f.^*^^no one^#^^#^pronoun^#^^^', 
'13^%^noceō^,^noc$ēre^,^nocu$ī^,^nocit$us^^*^^be harmful, harm (+ dat.)^#^2^#^verb^#^^^', 
'13^%^ōrātiō^,^ōrātiōn$is^,^^,^^f.^*^^oration, speech^#^3^#^noun^#^^^', 
'13^%^paene^,^^,^^,^^^*^^almost^#^^#^adverb^#^^^', 
'13^%^parcō^,^parc$ere^,^peperc$ī^,^pars$us^^*^^be sparing, spare (+ dat.)^#^3^#^verb^#^^^', 
'13^%^pāreō^,^pār$ēre^,^pāru$ī^,^pārit$us^^*^^be obedient, obey (+ dat.)^#^2^#^verb^#^^^', 
'13^%^persuādeō^,^persuād$ēre^,^persuās$ī^,^persuās$us^^*^^be persuasive, persuade (+ dat.)^#^2^#^verb^#^^^', 
'13^%^plēbs^,^plēb$is^,^^,^^f.^*^^common people^#^3^#^noun^#^^^', 
'13^%^praeferō^,^praefer$re^,^praetul$ī^,^praelāt$us^^*^^bring (place) before, prefer^#^^#^verb^#^compound; irregular in present system^^', 
'13^%^praeficiō^,^praefic$ere^,^praefēc$ī^,^praefect$us^^*^^make before (at the head of), put in command of^#^3i^#^verb^#^compound^^', 
'13^%^praesum$^,^praees$se^,^praefu$ī^,^--^^*^^be before (at the head of), be  in command of^#^^#^verb^#^compound^^', 
'13^%^quis^,^quid^,^^,^^^*^^someone, something^#^^#^pronoun^#^^^', 
'13^%^quī^,^quae^,^quod^,^^^*^^some, any^#^^#^adjective^#^irregular^^', 
'13^%^quisque^,^quidque / quicque^,^^,^^^*^^each one, each thing, every one, every thing^#^^#^pronoun^#^^^', 
'13^%^quīque^,^quaeque^,^quodque^,^^^*^^each, every^#^^#^adjective^#^irregular^^', 
'13^%^quō^,^^,^^,^^^*^^(to) where^#^^#^adverb^#^^^', 
'13^%^sollers^,^sollert$is^,^^,^^^*^^skilled, expert^#^3^#^adjective^#^^^', 
'13^%^studeō^,^stud$ēre^,^studu$ī^,^--^^*^^be zealous, study (+ dat.)^#^2^#^verb^#^^^', 
'13^%^ūsus^,^ūs$ūs^,^^,^^m.^*^^use,, advantage, enjoyment^#^4^#^noun^#^^^', 
'13^%^vix^,^^,^^,^^^*^^hardly, scarcely^#^^#^adverb^#^^^', 
'^^^^^^^^^^^^^^^^^^^^', 
'14^%^accidō^,^accid$ere^,^accid$ī^,^--^^*^^fall upon, happen, occur^#^3^#^verb^#^^^', 
'14^%^adeō^,^^,^^,^^^*^^so, so much, so far^#^^#^adverb^#^^^', 
'14^%^adveniō^,^adven$īre^,^advēn$ī^,^advent$us^^*^^come to, arrive^#^4^#^verb^#^^^', 
'14^%^animus^,^anim$ī^,^^,^^m.^*^^mind, rational spirit, soul^#^2^#^noun^#^^^', 
'14^%^auctōritās^,^auctōritāt$is^,^^,^^f.^*^^authority^#^3^#^noun^#^^^', 
'14^%^aut^,^^,^^,^^^*^^or^#^^#^coordinating conjunction^#^^^', 
'14^%^aut…aut^,^^,^^,^^^*^^either…or^#^^#^phrase^#^^^', 
'14^%^Carthāgō^,^Carthāgin$is^,^^,^^f.^*^^Carthage, a city on the coast of  North Africa^#^3^#^noun^#^^^', 
'14^%^colloquor^,^colloqu$ī^,^collocūtus sum^,^^^*^^speak, talk, converse with^#^3^#^verb^#^deponent^^', 
'14^%^dīgnus^,^dīgn$a^,^dīgnum^,^^^*^^worthy, deserving, suitable + abl.^#^2/1/2^#^adjective^#^^^', 
'14^%^indīgnus^,^indīgn$a^,^indīgnum^,^^^*^^unworthy, unsuitable + abl.^#^2/1/2^#^adjective^#^^^', 
'14^%^dolor^,^dolōr$is^,^^,^^m.^*^^pain, grief, sorrow^#^3^#^noun^#^^^', 
'14^%^efficiō^,^effic$ere^,^effēc$ī^,^effect$us^^*^^effect, bring about ^#^3i^#^verb^#^^^', 
'14^%^etiam^,^^,^^,^^^*^^even^#^^#^adverb^#^^^', 
'14^%^hūc^,^^,^^,^^^*^^to this place^#^^#^adverb^#^^^', 
'14^%^illūc^,^^,^^,^^^*^^to that place^#^^#^adverb^#^^^', 
'14^%^intendō^,^intend$ere^,^intend$ī^,^intent$us^^*^^stretch out, extend, aim, exert^#^3^#^verb^#^^^', 
'14^%^inter^,^^,^^,^^^*^^between, among^#^^#^preposition^#^+ acc.^^', 
'14^%^ita^,^^,^^,^^^*^^so, in this way^#^^#^adverb^#^^^', 
'14^%^modo^,^^,^^,^^^*^^only; just, just now^#^^#^adverb^#^^^', 
'14^%^nōtus^,^nōt$a^,^nōtum^,^^^*^^known, well-known, customary^#^2/1/2^#^adjective^#^^^', 
'14^%^nūntiō^,^nūnti$āre^,^nūntiāv$ī^,^nuntiāt$us^^*^^report, announce^#^1^#^verb^#^^^', 
'14^%^nūntius^,^nūnti$ī^,^^,^^m.^*^^messenger, message^#^2^#^noun^#^^^', 
'14^%^nūper^,^^,^^,^^^*^^recently^#^^#^adverb^#^^^', 
'14^%^ōs^,^ōr$is^,^^,^^n.^*^^mouth, expression^#^3^#^noun^#^^^', 
'14^%^ostendō^,^onstend$ere^,^ostend$ī^,^ostent$us^^*^^show, expose, make plain^#^3^#^verb^#^^^', 
'14^%^parō^,^par$āre^,^parāv$ī^,^parāt$us^^*^^prepare, make ready, provide, get^#^1^#^verb^#^^^', 
'14^%^paulus^,^paul$a^,^paulum^,^^^*^^little, small^#^2/1/2^#^adjective^#^comp. degree of minimus, a, um^^', 
'14^%^pāx^,^pāc$is^,^^,^^f.^*^^peace^#^3^#^noun^#^^^', 
'14^%^polliceor^,^pollic$ērī^,^pollicit$us sum^,^^^*^^promise^#^2^#^verb^#^deponent^^', 
'^%^properō^,^proper$āre^,^properāv$ī^,^properāt$us^^*^^hasten^#^1^#^verb^#^^^', 
'14^%^quālis^,^quāl$e^,^^,^^^*^^of what kind, what kind of^#^3^#^adjective^#^relative, interrogative^^', 
'14^%^rīdeō^,^rīd$ēre^,^rīs$ī^,^rīs$us^^*^^laugh (at)^#^2^#^verb^#^^^', 
'14^%^senex^,^sen$is^,^^,^^^*^^old^#^3^#^adjective^#^^^', 
'14^%^sīc^,^^,^^,^^^*^^so, in this way^#^^#^adverb^#^^^', 
'14^%^tālis^,^tāl$e^,^^,^^^*^^such, of such a sort^#^3^#^adjective^#^correlative^^', 
'14^%^tālis…quālis^,^^,^^,^^^*^^such…as ^#^^#^relative/correlative pair^#^^^', 
'14^%^tempestās^,^tempestāt$is^,^^,^^f.^*^^weather, storm, season^#^3^#^noun^#^^^', 
'14^%^trāns^,^^,^^,^^^*^^across, on the other side of^#^^#^preposition^#^+ acc.^^', 
'14^%^tum / tunc^,^^,^^,^^^*^^then, at that time^#^^#^adverb^#^^^', 
'14^%^ubīque^,^^,^^,^^^*^^everywhere, anywhere, wherever^#^^#^adverb^#^^^', 
'14^%^vēritās^,^vēritāt$is^,^^,^^f.^*^^truth^#^^#^^#^^^', 
'14^%^vincō^,^vinc$ere^,^vīc$ī^,^vict$us^^*^^conquer, beat, overcome^#^3^#^verb^#^^^', 
'***^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'15^%^absum$^,^abes$se^,^āfu$ī^,^āfutūr$us^^*^^be away, be absent^#^^#^^#^^^', 
'15^%^absēns^,^absent$is^,^^,^^^*^^absent^#^^#^^#^^^', 
'15^%^adsum$^,^ades$se^,^adfu$ī^,^--^^*^^be present^#^^#^^#^^^', 
'15^%^agitō^,^agit$āre^,^agitāv$ī^,^agitāt$us^^*^^disturb, stir up^#^^#^^#^^^', 
'15^%^antequam^,^^,^^,^^^^^before^#^^#^^#^^^', 
'15^%^appāreō^,^appār$ēre^,^appāru$ī^,^apparit$us^^^^appear, come in sight, be apparent^#^^#^^#^^^', 
'15^%^calamitās^,^calamitāt$is^,^^,^^f.^^^disaster, calamity^#^^#^^#^^^', 
'15^%^contrā^,^^,^^,^^^^^against, facing; opposite, in opposition^#^^#^^#^^^', 
'15^%^cum ^,^^,^^,^^^^^CONJUNCTION = when, since, although // PREPOSITION = with (+ abl.)^#^^#^^#^^^', 
'15^%^dēsinō^,^dēsin$ere^,^dēsi$ī^,^--^^^^stop, cease (frequently with infinitve or ablative: pūgnāre dēsiit, ‘he stopped fighting’; ‘inimīcitiā dēsiit, ‘he stopped (his) hostility’)^#^^#^^#^^^', 
'15^%^dōnec^,^^,^^,^^^^^while, until, as long, as^#^^#^^#^^^', 
'15^%^dum^,^^,^^,^^^^^while , until, as long as; if only, provided that^#^^#^^#^^^', 
'15^%^dummodo^,^^,^^,^^^^^if only, provided that^#^^#^^#^^^', 
'15^%^etsī^,^^,^^,^^^^^although, even if (+ indic.)^#^^#^^#^^^', 
'15^%^exiguus^,^exigu$a^,^exiguum^,^^^^^small^#^^#^^#^^^', 
'15^%^exspectō^,^exspect$āre^,^exspectāv$ī^,^exspectāt$us^^^^wait (for), expect^#^^#^^#^^^', 
'15^%^fore^,^^,^^,^^^^^= futūrus, -a, -um esse (future infinitive of sum)^#^^#^^#^^^', 
'15^%^fors^,^fort$is^,^fortium^,^^f.^^^chance^#^^#^^#^^^', 
'15^%^fulgor^,^fulgōr$is^,^^,^^m.^^^lightning, flash, brightness^#^^#^^#^^^', 
'15^%^grātus^,^grāt$a^,^grātum^,^^^^^pleasing (+ dat.)^#^^#^^#^^^', 
'15^%^igitur^,^^,^^,^^^^^therefore^#^^#^^#^^^', 
'15^%^ingenium^,^ingeni$ī^,^^,^^n.^^^nature, talent, disposition, natural quality^#^^#^^#^^^', 
'15^%^inimīcitia^,^inimīciti$ae^,^^,^^f.^^^hostility^#^^#^^#^^^', 
'15^%^interdum^,^^,^^,^^^^^sometimes^#^^#^^#^^^', 
'15^%^iūdex^,^iūdic$is^,^^,^^m.^^^judge; jury (pl.)^#^^#^^#^^^', 
'15^%^iūdicium^,^iūdici$ī^,^^,^^n.^^^trial, judgment, decision^#^^#^^#^^^', 
'15^%^memoria^,^memori$ae^,^^,^^f.^^^memory^#^^#^^#^^^', 
'15^%^misceō^,^misc$ēre^,^miscu$ī^,^mixt$us^^^^mix, intermingle, blend^#^^#^^#^^^', 
'15^%^modo^,^^,^^,^^^^^if only, provided that^#^^#^^#^^^', 
'15^%^nusquam^,^^,^^,^^^^^nowhere^#^^#^^#^^^', 
'15^%^nūtrīx^,^nūtrīc$is^,^^,^^f.^^^nurse^#^^#^^#^^^', 
'15^%^occidō^,^occid$ere^,^occid$ī^,^occās$us^^^^fall, set, die^#^^#^^#^^^', 
'15^%^omnīnō^,^^,^^,^^^^^all in all, as a whole, entirely^#^^#^^#^^^', 
'15^%^pereō^,^per$īre^,^peri$ī (perīv$ī)^,^perit$us^^^^die, perish^#^^#^^#^^^', 
'15^%^priusquam^,^^,^^,^^^^^before^#^^#^^#^^^', 
'15^%^prōsum$^,^prōdes$se^,^prōfu$ī^,^--^^^^be useful, do good, benefit, profit (+ dat.)^#^^#^^#^^^', 
'15^%^putō^,^put$āre^,^putāv$ī^,^putāt$us^^^^think^#^^#^^#^^^', 
'15^%^quamvīs^,^^,^^,^^^^^although (+ subjunctive)^#^^#^^#^^^', 
'15^%^quasi^,^^,^^,^^^^^as if, as it were^#^^#^^#^^^', 
'15^%^quidem^,^^,^^,^^^^^indeed^#^^#^^#^^^', 
'15^%^nē … quidem^,^^,^^,^^^^^not even^#^^#^^#^^^', 
'15^%^quōad^,^^,^^,^^^^^as long as, as far as, until (takes same construction as dum and dōnec)^#^^#^^#^^^', 
'15^%^quoniam^,^^,^^,^^^^^since (+ indicative)^#^^#^^#^^^', 
'15^%^redeō^,^red$īre^,^redi$ī^,^redit$us^^^^return, go back^#^^#^^#^^^', 
'15^%^simul ac (simul atque)^,^^,^^,^^^^^as soon as (+ indicative)^#^^#^^#^^^', 
'15^%^somnus^,^somn$ī^,^^,^^m.^^^sleep, dream^#^^#^^#^^^', 
'15^%^supersum$^,^superes$se^,^superfu$ī^,^--^^^^be left over, survive^#^^#^^#^^^', 
'15^%^ubi^,^^,^^,^^^^^when^#^^#^^#^^^', 
'^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'^%^^,^^,^^,^^^*^^^#^^#^^#^^^', 
'***^%^***^,^***^,^***^,^***^***^*^^^#^^#^^#^^^', 
'16^%^abeō^,^abīre^,^abiī (abīvī)^,^abitus^^*^^go away, depart^#^^#^^#^^^', 
'16^%^adversus^,^adversa^,^adversum^,^^^*^^opposite, hostile, adverse^#^^#^^#^^^', 
'16^%^aliēnus^,^aliēna^,^aliēnum^,^^^*^^belonging to another, strange^#^^#^^#^^^', 
'16^%^āmittō^,^āmittere^,^āmīsī^,^āmissus^^*^^let go, lose^#^^#^^#^^^', 
'16^%^aperiō^,^aperīre^,^aperuī^,^apertus^^^^open^#^^#^^#^^^', 
'16^%^causa^,^causae^,^^,^^f.^^^cause, reason^#^^#^^#^^^', 
'16^%^causā (preceded by the genitive)^,^^,^^,^^^^^for the sake of^#^^#^^#^^^', 
'16^%^cottīdiē (or cotīdiē)^,^^,^^,^^^^^daily^#^^#^^#^^^', 
'16^%^decōrus^,^decōra^,^decōrum^,^^^^^fitting, suitable; handsome^#^^#^^#^^^', 
'16^%^dēsum^,^dēesse^,^dēfuī^,^--^^^^be missing, fail (often + dat.)^#^^#^^#^^^', 
'16^%^discō^,^discere^,^didicī^,^--^^^^learn^#^^#^^#^^^', 
'16^%^frūstrā^,^^,^^,^^^^^in vain^#^^#^^#^^^', 
'16^%^īnfirmus^,^īnfirma^,^īnfirmum^,^^^^^weak, unhealthy^#^^#^^#^^^', 
'16^%^īnstituō^,^īnstituere^,^īnstituī^,^īnstitūtus^^^^set (up), establish, arrange^#^^#^^#^^^', 
'16^%^interest^,^interesse^,^interfuit^,^--^^^^it is of importance, it concerns, it is of interest^#^^#^^#^^^', 
'16^%^lābor^,^lābī^,^lāpsus sum^,^^^^^slip, glide, fall^#^^#^^#^^^', 
'16^%^lēx^,^lēgis^,^^,^^^^^law^#^^#^^#^^^', 
'16^%^libenter^,^^,^^,^^^^^freely, willingly, gladly^#^^#^^#^^^', 
'16^%^licet^,^licēre^,^licuit (licitum est)^,^^^^^it is permitted^#^^#^^#^^^', 
'16^%^miseret^,^miserēre^,^miseruit (miseritum est)^,^^^^^it pities, it moves to pity^#^^#^^#^^^', 
'16^%^necesse^,^^,^^,^^^^^necessary^#^^#^^#^^^', 
'16^%^oportet^,^oportēre^,^oportuit^,^--^^^^it is necessary, it is proper^#^^#^^#^^^', 
'16^%^paenitet^,^paenitēre^,^paenituit^,^--^^^^it repents^#^^#^^#^^^', 
'16^%^piget^,^pigēre^,^piguit (pigitum est)^,^^^^^it disgusts^#^^#^^#^^^', 
'16^%^pudet^,^pudēre^,^puduit (puditum est)^,^^^^^it shames^#^^#^^#^^^', 
'16^%^rēfert^,^rēferre^,^rētulit^,^--^^^^it is of importance^#^^#^^#^^^', 
'16^%^scrīptor^,^scrīptōr$is^,^^,^^m.^^^writer^#^^#^^#^^^', 
'16^%^stō^,^st$āre^,^stet$ī^,^stāt$us^^^^stand^#^^#^^#^^^', 
'16^%^studiōsus^,^studiōsa^,^studiōsum^,^^^^^fon of, partial to, studious (+ gen.)^#^^#^^#^^^', 
'16^%^sustineō^,^sustin$ēre^,^sustinu$ī^,^sustent$us^^^^support, maintain^#^^#^^#^^^', 
'16^%^taedet^,^taed$ēre^,^taedu$it (taesum est)^,^^^^^it bores, it disgusts^#^^#^^#^^^', 
'16^%^ūtilis^,^ūtil$e^,^^,^^^^^useful, beneficial^#^^#^^#^^^', 
'16^%^vel^,^^,^^,^^^^^or^#^^#^^#^^^', 
'16^%^vel…vel...^,^^,^^,^^^^^either…or^#^^#^^#^^^', 
'16^%^vetus^,^veter$is^,^^,^^^^^old^#^^#^^#^^^', 
'16^%^violō^,^viol$āre^,^violāv$ī^,^violāt$us^^^^do violence to, break (an agreement, the law)^#^^#^^#^^^', 
'^%^^,^^,^^,^^^^^^#^^#^^#^^^', 
'***^%^***^,^***^,^***^,^***^***^*^^^#^^#^^#^^^', 
'17^%^aetās^,^aetāt$is^,^^,^^f.^*^^time of life, age, life^#^^#^^#^^^', 
'17^%^celeritās^,^celeritāt$is^,^^,^^f.^*^^speed, swiftness^#^^#^^#^^^the c in e=mc squared stands for celeritas (i.e. the speed of light)', 
'17^%^dēfendō^,^dēfend$ere^,^dēfend$ī^,^dēfēns$us^^*^^defend^#^^#^^#^^^', 
'17^%^dēnique^,^^,^^,^^^*^^finally, at last^#^^#^^#^^^', 
'17^%^dēsistō^,^dēsist$ere^,^dēstit$ī^,^dēstit$us^^*^^stop, desist^#^^#^^#^^^', 
'17^%^dēterreō^,^dēterr$ēre^,^dēterru$ī^,^dēterrit$us^^*^^deter, prevent, hinder, keep from^#^^#^^#^^^', 
'17^%^dubius^,^dubi$a^,^dubium^,^^^*^^doubtful^#^^#^^#^^^', 
'17^%^dubium^,^dubi$ī^,^^,^^n.^*^^doubt, hesitation^#^^#^^#^^^', 
'17^%^dubitō^,^dubit$āre^,^dubitāv$ī^,^dubitāt$us^^*^^hesitate (+ inf.); doubt (+ ind. question OR quīn + subjunctive)^#^^#^^#^^^', 
'17^%^impediō^,^imped$īre^,^impedīv$ī/impedi$ī^,^impedīt$us^^*^^deter, impede, prevent^#^^#^^#^^^', 
'17^%^metuō^,^metu$ere^,^metu$ī^,^--^^*^^fear^#^^#^^#^^^', 
'17^%^nemus^,^nemor$is^,^^,^^n.^*^^grove, wood^#^^#^^#^^^', 
'17^%^obitus^,^obit$ūs^,^^,^^m.^*^^a going down, setting; downfall, ruin^#^^#^^#^^^', 
'17^%^obstō^,^obst$āre^,^obstit$ī^,^obstāt$us^^*^^stand in the way of, hinder (+ dat.)^#^^#^^#^^^', 
'17^%^orior^,^or$īrī^,^ort$us sum^,^^^*^^rise, arise, begin^#^^#^^#^^^', 
'17^%^ortus^,^ort$ūs^,^^,^^m.^*^^rising, source^#^^#^^#^^^', 
'17^%^perveniō^,^perven$īre^,^pervēn$ī^,^pervent$us^^*^^arrive (at) (+ ad)^#^^#^^#^^^', 
'17^%^prohibeō^,^prohib$ēre^,^prohibu$ī^,^prohibit$us^^*^^keep from, prohibit, prevent^#^^#^^#^^^', 
'17^%^quīn^,^^,^^,^^^*^^but that, that not (used after expressions of prevention, negative doubting, etc.)^#^^#^^#^^^', 
'17^%^quōminus^,^^,^^,^^^*^^by which the less, that not, from (used in positive or negative clauses of prevention)^#^^#^^#^^^', 
'17^%^radius^,^radi$ī^,^^,^^m.^*^^rod, ray^#^^#^^#^^^', 
'17^%^religiō^,^religiōn$is^,^^,^^f.^*^^religious awe, reverence, integrity, sanctity^#^^#^^#^^^', 
'17^%^relinquō^,^relinqu$ere^,^relīqu$ī^,^relict$us^^*^^leave behind, abandon^#^^#^^#^^^', 
'17^%^reliquus^,^reliqu$a^,^reliquum^,^^^*^^remaining; rest of^#^^#^^#^^^', 
'17^%^retegō^,^reteg$ere^,^retēx$ī^,^retēct$us^^*^^uncover, reveal^#^^#^^#^^^', 
'17^%^tergum^,^terg$ī^,^^,^^n.^*^^back^#^^#^^#^^^', 
'17^%^turpis^,^turp$e^,^^,^^^*^^foul, ugly^#^^#^^#^^^', 
'17^%^ūnā^,^^,^^,^^^*^^together, at the same time^#^^#^^#^^^', 
'17^%^vēnor^,^vēn$ārī^,^vēnāt$us sum^,^^^*^^hunt, go hunting ^#^^#^^#^^^', 
'17^%^vertō^,^vert$ere^,^vert$ī^,^vers$us^^*^^turn^#^^#^^#^^^', 
'17^%^animadvertō^,^animadvert$ere^,^animadvert$ī^,^animadvers$us^^*^^turn one’s attention to, notice^#^^#^^#^^^', 
'17^%^vetō^,^vet$āre^,^vetu$ī^,^vetit$us^^*^^forbid^#^^#^^#^^^', 
'****^%^****^,^****^,^****^,^^^^^^#^^#^^#^^^', 
'18^%^aestimō^,^aestim$āre^,^aestimāv$ī^,^aestimāt$us^^*^^estimate, reckon^#^^#^^#^^^', 
'18^%^as^,^ass$is^,^-ium^,^^m.^*^^as (a small denomination of money)^#^^#^^#^^^', 
'18^%^cingō^,^cing$ere^,^cīnx$ī^,^cīnct$us^^*^^surround, gird^#^^#^^#^^^', 
'18^%^emō^,^em$ere^,^ēm$ī^,^ēmpt$us^^*^^buy^#^^#^^#^^^', 
'18^%^honor^,^honōr$is^,^^,^^m.^^^honor, distinction, office^#^^#^^#^^^', 
'18^%^meminī^,^memin$isse^,^^,^^^^^remember^#^^#^^#^^^', 
'18^%^nihilum^,^nihil$ī^,^^,^^n.^^^nothing^#^^#^^#^^^', 
'18^%^numerus^,^numer$ī^,^^,^^m.^^^number^#^^#^^#^^^', 
'18^%^oblīvīscor^,^oblīvīsc$ī^,^oblīt$us sum^,^^^^^forget^#^^#^^#^^^', 
'18^%^pretium^,^preti$ī^,^^,^^n.^^^price; value^#^^#^^#^^^', 
'18^%^pūgna^,^pūgn$ae^,^^,^^f.^^^battle, fight^#^^#^^#^^^', 
'18^%^quod sī^,^^,^^,^^^^^but if^#^^#^^#^^^', 
'18^%^vendō^,^vend$ere^,^vendid$ī^,^vendit$us^^^^sell^#^^#^^#^^^', 
'18^%^vulnerō^,^vulner$āre^,^vulnerāv$ī^,^vulnerāt$us^^^^wound^#^^#^^#^^^'
];