var kck_levels = {
    //start with just variation in the middle element 3s only (v1-3 only)
    'test 1': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': {'true': 0.5, 'false': 0.5},
        // 'verb_dashes_removed': true
    },
    '1': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        // 'verb_dashes_removed': {'english': 0.5, 'latin': 0.5},
        // 'verb_dashes_removed': {true: 0.5, false: 0.5},
        'verb_dashes_removed': false
    },
    // adding 3p
    '10': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding more verbs
    '20': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding conjunctions et and sed and aut (while reducing verbs)
    '30': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // increasing vocabulary to full set
    '40': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding passives all tenses (because of 1-tense-bug) 3s only limited verbs
    '50': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        // 'universal_indicative_tenses_allowed' : ['present indicative'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding 3p
    '60': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        // 'universal_indicative_tenses_allowed' : ['present indicative'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding all tenses still limited verbs
    '70': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding all verbs
    '80': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding all conjunctions
    '90': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    
    //adding 1s-3p
    // all cases where 1s-3p are used and person is in the drop down path
    // must be set to latin --> english because otherwise it's too easy
    // need to fix this down the road
    '100': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        // 'voice' : ['active'],
        'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding 1s-3p
    '110': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding more verbs
    '120': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding conjunctions et and sed and aut (while reducing verbs)
    '130': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // increasing vocabulary to full set
    '140': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding passives all tenses (because of 1-tense-bug) 3s only limited verbs
    '150': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        // 'universal_indicative_tenses_allowed' : ['present indicative'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding 3p
    '160': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        // 'universal_indicative_tenses_allowed' : ['present indicative'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding all tenses still limited verbs
    '170': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or',],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        // 'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
        //     'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
        //     'hear', 'shout', 'speak', 'see'
        //     ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // adding all verbs
    '180': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding all conjunctions
    '190': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    ///////////////////
    // now we alternate between english --> latin and latin ---> english
    // E--> L
    '200': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        'drop_down_path' : ['lexeme', 'voice'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        'source_language' : {'english': 1, 'latin': 0},
        'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // L --> E
    '210': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // E--> L
    '220': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        'drop_down_path' : ['lexeme', 'voice'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        'source_language' : {'english': 1, 'latin': 0},
        'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // L --> E
    '230': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        'allowed_conjunctions': ['c_null'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    //adding all conjunctions
    
    // E--> L
    '240': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        'drop_down_path' : ['lexeme', 'voice'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        'source_language' : {'english': 1, 'latin': 0},
        'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // L --> E
    '250': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    // E--> L
    '260': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        'drop_down_path' : ['lexeme', 'voice'],
        // 'drop_down_path' : ['lexeme', 'voice', 'tense_and_mood'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        'source_language' : {'english': 1, 'latin': 0},
        'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    
    // L --> E
    '270': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    ///////
    ///dashes removed below
    '310': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active', 'passive'],
        // 'voice' : ['active', 'passive'],
        // 'person_and_number' : ['3s'],
        // 'person_and_number' : ['3s', '3p'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        // 'person_and_number' : ['1s'],
        // 'allowed_conjunctions': ['c_null'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        // 'allowed_verbs' : ['love', 'speak', 'carry', 'attack', 'fear', 'rule', 'grab'],
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear',
            'rule', 'grab', 'carry', 'scare', 'fill', 'eat', 'come', 'command', 
            'hear', 'shout', 'speak', 'see'
            ],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : [ 'time', 'lexeme', 'voice', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        // 'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        'drop_down_path' : ['lexeme', 'voice'],
        // 'drop_down_path' : ['lexeme', 'voice', 'tense_and_mood'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.5, 'intransitive': 0.5},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        // 'source_language' : {'english': 0, 'latin': 1},
        // 'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        // 'verb_dashes_removed': false,
        'verb_dashes_removed': true
    },
    /////////////
    // below are unprocessed levels, don't use
    '560': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative'],
        'voice' : ['active'],
        // 'voice' : ['active', 'passive'],
        'person_and_number' : ['3s', '3p'],
        // 'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and'],
        // 'allowed_conjunctions': ['c_null', 'c_and', 'c_or', 'c_but', 'c_purpose', 'c_when', 'c_why'],
        // 'allowed_conjunctions': ['c_why'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear'],
        // 'allowed_verbs' : ['speak', 'attack'],
        'noun_switch' : false,
        'allowed_nouns': ['wolf'],
        // 'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number'],
        'drop_down_path' : ['lexeme', 'voice', 'person_and_number'],
        // 'drop_down_path' : ['lexeme', 'person_and_number'],
        // 'drop_down_path' : ['lexeme'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.9, 'intranstive': 0.1},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0, 'latin': 1},
        'target_language' : {'english': 1, 'latin': 0},
        // 'source_language' : {'english': 1, 'latin': 0},
        // 'target_language' : {'english': 0, 'latin': 1},
        // 'source_language' : {'english': 0.5, 'latin': 0.5},
        // 'target_language' : {'english': 0.5, 'latin': 0.5},
        'terminology_display_dictionary': 'basic',
        // 'terminology_display_dictionary': 'advanced',
        'verb_dashes_removed': false,
        // 'verb_dashes_removed': true
    },
    ///////INTRO OF ALL PERSONAL ENDINGS
    //vary endings 1s-3p with present tense only (limited verbs)
    '570': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative', 'greek perfect indicative', 'aorist indicative'],
        // 'voice': ['active'],
        'voice' : ['active', 'passive'],
        'person_and_number' : ['3s', '3p'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_purpose', 'c_when', 'c_why', 'c_if_flv', 'c_if_fmv', 'c_cum_because'],
        'red herring': 'false',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear'],
        'allowed_nouns': ['wolf'],
        'noun_switch' : false,
        'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number', 'sequence'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.9, 'intranstive': 0.1},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 1, 'latin': 0},
        'target_language' : {'english': 0, 'latin': 1},
        //setting for default display
        'terminology_display_dictionary': 'basic',
        'verb_dashes_removed': false
    },
    // all active endings, all tenses (limited verbs)
    '580': {
        'time': ['simultaneous', 'prior', 'subsequent'],
        'sequence': ['primary', 'secondary'],
        'universal_indicative_tenses_allowed' : ['present indicative', 'future indicative', 
            'imperfect indicative', 'greek perfect indicative', 'aorist indicative'],
        // 'voice': ['active'],
        'voice' : ['active', 'passive'],
        'person_and_number' : ['1s', '2s', '3s', '1p', '2p', '3p'],
        'allowed_conjunctions': ['c_null', 'c_and', 'c_purpose', 'c_when', 'c_why', 'c_if_flv', 'c_if_fmv', 'c_cum_because'],
        'red herring': 'true',
        'absolute-relative-split': 'on',
        'allowed_verbs' : ['love', 'speak', 'command', 'attack', 'fear'],
        'allowed_nouns': ['wolf'],
        'noun_switch' : false,
        'drop_down_path' : ['lexeme', 'voice', 'time', 'tense_and_mood','person_and_number', 'sequence'],
        'drop_down_path_noun' : ['lexeme', 'case'],
        'transitivity' : {'transitive': 0.9, 'intransitive': 0.1},
        'explicitness' : {'explicit': 0.9, 'implicit': 0.1},
        'source_language' : {'english': 0.5, 'latin': 0.5},
        'target_language' : {'english': 0.5, 'latin': 0.5},
        //setting for default display
        'terminology_display_dictionary': 'basic',
        'verb_dashes_removed': false
    }
    // all active endings, all tenses (many verbs)
    ///////INTRO OF PASSIVE
    // 3s active and passive present only (limited verbs)
    // 3s active and passive all tenses (limited verbs)
    // 3s & 3p active and passive all tenses (limited verbs)
    // 3s & 3p active and passive all tenses (many verbs)
    // 1s - 3p active and passive all tenses (limited verbs)
    // 1s - 3p active and passive all tenses (many verbs)
}