// this is our main function
// argument: a features dictionary called component (can be specified at will or generated by a kck generating function)
// returns: a latin form
// the component contains all relevant information
// lexeme, tense, mood, voice, person_number

var inflect_latin_verb_main = function (component) {
    //a few properties can be simply read straight off the component
    var tense = component.tense_mood_voice[0];
    var mood = componentt.tense_mood_voice[1];
    var voice = component.tense_mood_voice[2];

    if (tense === 'future' && mood === 'subjunctive') 
    
    
    
    var root = get_root(component);
    var in_perfect_system = get_latin_verb_system(component)
    === 'perfect system';
    
    
    var output;
}
